% Generated by morkl.generateOpenProgramProofArtifacts
% nqueens-4-full-program: axiomatized structural full-program schema consistency
% Full pure 4-queens program.
%
% This structural ATP tier emits the generated full MORKL program as a DAG
% of first-order terms and checks that it is well formed under the declared
% backend membership contracts. Source/backend agreement is axiomatized per
% constructor below; consequently the final theorem is a schema-consistency
% check, not an independent proof about the Scala implementations. Iter is modeled with
% an explicit binding environment; Range is modeled as source membership plus
% ordered-rank selection. The remaining hard operators are named explicitly
% as shared semantic predicates rather than hidden behind bounded enumeration.
% General Fixpoint is exposed as the union-saturating base-or-step equation
% over the structural environment; leastness/positivity remains a proof
% obligation for future lowering-specific lemmas rather than a runtime cap.

% Abstract path and input interpretation.
fof(path_ref_sem, axiom, ! [P,R] : (path_matches(P,path_ref(R)) <=> path_ref_mem(P,R))).
fof(path_concat_sem, axiom,
  ! [P,A,B] : (path_matches(P,path_concat(A,B)) <=>
    ? [Q,R] : (path_matches(Q,A) & path_matches(R,B) & p_append(Q,R,P)))).
fof(path_grounded_pp_sem, axiom, ! [P,Q] : (path_matches(P,path_grounded_pp(Q)) <=> grounded_path_path_sem(P,Q))).
fof(path_grounded_sp_sem, axiom, ! [P,S] : (path_matches(P,path_grounded_sp(S)) <=> grounded_space_path_sem(P,S))).

fof(path_item_sem, axiom, ! [P,I] : (path_matches(P,path_item(I)) <=> P = cons(I,nil))).
fof(path_env_lit_sem, axiom, ! [P,X,Env] : (path_env_matches(P,path_lit(X),Env) <=> path_matches(P,path_lit(X)))).
fof(path_env_item_sem, axiom, ! [P,I,Env] : (path_env_matches(P,path_item(I),Env) <=> P = cons(I,nil))).
fof(path_env_concat_sem, axiom,
  ! [P,A,B,Env] : (path_env_matches(P,path_concat(A,B),Env) <=>
    ? [Q,R] : (path_env_matches(Q,A,Env) & path_env_matches(R,B,Env) & p_append(Q,R,P)))).
fof(path_env_grounded_pp_sem, axiom, ! [P,Q,Env] : (path_env_matches(P,path_grounded_pp(Q),Env) <=> grounded_path_path_env_sem(P,Q,Env))).
fof(path_env_grounded_sp_sem, axiom, ! [P,S,Env] : (path_env_matches(P,path_grounded_sp(S),Env) <=> grounded_space_path_env_sem(P,S,Env))).

fof(path_lookup_hit, axiom,
  ! [P,R,Q,Outer] : (path_lookup_matches(P,R,env_path(R,Q,Outer)) <=> path_env_matches(P,Q,Outer))).
fof(path_lookup_miss_path, axiom,
  ! [P,R,Other,Q,Outer] : (R != Other => (path_lookup_matches(P,R,env_path(Other,Q,Outer)) <=> path_lookup_matches(P,R,Outer)))).
fof(path_lookup_skip_space, axiom,
  ! [P,R,Name,S,Outer] : (path_lookup_matches(P,R,env_space(Name,S,Outer)) <=> path_lookup_matches(P,R,Outer))).
fof(path_lookup_empty, axiom, ! [P,R] : (path_lookup_matches(P,R,env_empty) <=> path_ref_mem(P,R))).
fof(path_env_ref_sem, axiom, ! [P,R,Env] : (path_env_matches(P,path_ref(R),Env) <=> path_lookup_matches(P,R,Env))).

% Range is order-sensitive.  The structural FOL layer exposes the exact
% shape of the implementation contract: membership in the source, a rank in
% that ordered source, normalized public bounds, and a half-open selected
% interval.  The rank/count/bounds relations are the remaining ordered-trie
% proof hooks; they are shared by all backends.
fof(range_select_rank, axiom,
  ! [P,A,Env,Start,End] : (range_select_env(P,A,Env,Start,End) <=>
    ? [K,N,Lo,Hi] : (
      range_rank_env(P,A,Env,K) &
      range_count_env(A,Env,N) &
      range_bounds(N,Start,End,Lo,Hi) &
      int_le(Lo,K) &
      int_lt(K,Hi)))).
fof(range_bounds_full_sentinel, axiom, ! [N] : range_bounds(N,n0,n0,n0,N)).
fof(range_bounds_empty_one_one, axiom, ! [N] : range_bounds(N,n1,n1,n0,n0)).
fof(range_bounds_functional, axiom,
  ! [N,Start,End,Lo1,Hi1,Lo2,Hi2] : (
    (range_bounds(N,Start,End,Lo1,Hi1) & range_bounds(N,Start,End,Lo2,Hi2)) =>
    (Lo1 = Lo2 & Hi1 = Hi2))).
fof(int_le_excludes_reverse_lt, axiom, ! [A,B] : (int_le(A,B) => ~int_lt(B,A))).

% Shared semantic frontiers for operators whose full FOL expansion still
% needs grounded host functions, folds, or least-fixed-point theory. They
% are per-operator, so generated certificates show exactly where stronger
% lemmas remain to be added.
fof(call_backend_shared, axiom, ! [P,R,Refs,Args] : (
  source_mem(P,op_call(R,Refs,Args)) <=>
  optimized_source_mem(P,op_call(R,Refs,Args)))).
fof(call_trie_shared, axiom, ! [P,R,Refs,Args] : (
  source_mem(P,op_call(R,Refs,Args)) <=> trie_mem(P,op_call(R,Refs,Args)))).
fof(call_zipper_shared, axiom, ! [P,R,Refs,Args] : (
  source_mem(P,op_call(R,Refs,Args)) <=> zipper_mem(P,op_call(R,Refs,Args)))).
fof(call_graph_shared, axiom, ! [P,R,Refs,Args] : (
  source_mem(P,op_call(R,Refs,Args)) <=> graph_mem(P,op_call(R,Refs,Args)))).

fof(source_empty, axiom,
  ! [P] : (~ source_mem(P,op_empty))).
fof(source_input, axiom,
  ! [P,X] : (source_mem(P,op_input(X)) <=> input_mem(P,X))).
fof(source_literal, axiom,
  ! [P,X] : (source_mem(P,op_literal(X)) <=> literal_mem(P,X))).
fof(source_singleton, axiom,
  ! [P,Q] : (source_mem(P,op_singleton(Q)) <=> path_matches(P,Q))).
fof(source_union, axiom,
  ! [P,A,B] : (source_mem(P,op_union(A,B)) <=> (source_mem(P,A) | source_mem(P,B)))).
fof(source_intersection, axiom,
  ! [P,A,B] : (source_mem(P,op_intersection(A,B)) <=> (source_mem(P,A) & source_mem(P,B)))).
fof(source_diff, axiom,
  ! [P,A,B] : (source_mem(P,op_diff(A,B)) <=> (source_mem(P,A) & ~ source_mem(P,B)))).
fof(source_restriction, axiom,
  ! [P,A,B] : (source_mem(P,op_restriction(A,B)) <=> (source_mem(P,A) & ? [Q] : (source_mem(Q,B) & p_prefix(Q,P))))).
fof(source_raffination, axiom,
  ! [P,A,B] : (source_mem(P,op_raffination(A,B)) <=> (source_mem(P,A) & ~ ? [Q] : (source_mem(Q,B) & p_prefix(Q,P))))).
fof(source_product, axiom,
  ! [P,A,B] : (source_mem(P,op_product(A,B)) <=> ? [Q,R] : (source_mem(Q,A) & source_mem(R,B) & p_append(Q,R,P)))).
fof(source_wrap, axiom,
  ! [P,A,Q] : (source_mem(P,op_wrap(A,Q)) <=> ? [Prefix,Tail] : (path_matches(Prefix,Q) & source_mem(Tail,A) & p_append(Prefix,Tail,P)))).
fof(source_unwrap, axiom,
  ! [P,A,Q] : (source_mem(P,op_unwrap(A,Q)) <=> ? [Prefix,Full] : (path_matches(Prefix,Q) & p_append(Prefix,P,Full) & source_mem(Full,A)))).
fof(source_tails_union, axiom,
  ! [P,A] : (source_mem(P,op_tails_union(A)) <=> ? [I] : source_mem(cons(I,P),A))).
fof(source_tails_intersection, axiom,
  ! [P,A] : (source_mem(P,op_tails_intersection(A)) <=> ((? [I,Q] : source_mem(cons(I,Q),A)) & ! [I] : ((? [Q] : source_mem(cons(I,Q),A)) => source_mem(cons(I,P),A))))).
fof(source_prefix_closure, axiom,
  ! [P,A] : (source_mem(P,op_prefix_closure(A)) <=> (P != nil & ? [Q] : (source_mem(Q,A) & p_prefix(P,Q))))).
fof(source_suffix_closure, axiom,
  ! [P,A] : (source_mem(P,op_suffix_closure(A)) <=> (P != nil & ? [Q] : (source_mem(Q,A) & p_suffix(P,Q))))).
fof(source_tails_closure, axiom,
  ! [P,A] : (source_mem(P,op_tails_closure(A)) <=> (((P = nil) & ? [Q] : source_mem(Q,A)) | (P != nil & ? [Q] : (source_mem(Q,A) & p_suffix(P,Q)))))).
fof(source_iter, axiom,
  ! [P,A,Sym,Rest,Body] : (source_mem(P,op_iter(A,Sym,Rest,Body)) <=> source_env_mem(P,op_iter(A,Sym,Rest,Body),env_empty))).
fof(source_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (source_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> fold_sem(P,A,Initial,Acc,Sym,Rest,Body,Update))).
fof(source_fixpoint, axiom,
  ! [P,A,Var,Step] : (source_mem(P,op_fixpoint(A,Var,Step)) <=> source_env_mem(P,op_fixpoint(A,Var,Step),env_empty))).
fof(source_grounded_ps, axiom,
  ! [P,Q] : (source_mem(P,op_grounded_ps(Q)) <=> grounded_ps_sem(P,Q))).
fof(source_grounded_ss, axiom,
  ! [P,A] : (source_mem(P,op_grounded_ss(A)) <=> grounded_ss_sem(P,A))).
fof(source_range, axiom,
  ! [P,A,Start,End] : (source_mem(P,op_range(A,Start,End)) <=> source_env_mem(P,op_range(A,Start,End),env_empty))).
fof(source_space_lookup_hit, axiom,
  ! [P,X,S,Outer] : (source_space_lookup_mem(P,X,env_space(X,S,Outer)) <=> source_env_mem(P,S,Outer))).
fof(source_space_lookup_miss_space, axiom,
  ! [P,X,Other,S,Outer] : (X != Other => (source_space_lookup_mem(P,X,env_space(Other,S,Outer)) <=> source_space_lookup_mem(P,X,Outer)))).
fof(source_space_lookup_skip_path, axiom,
  ! [P,X,R,Q,Outer] : (source_space_lookup_mem(P,X,env_path(R,Q,Outer)) <=> source_space_lookup_mem(P,X,Outer))).
fof(source_space_lookup_empty, axiom,
  ! [P,X] : (source_space_lookup_mem(P,X,env_empty) <=> input_mem(P,X))).
fof(source_env_empty, axiom,
  ! [P,Env] : (~ source_env_mem(P,op_empty,Env))).
fof(source_env_input, axiom,
  ! [P,X,Env] : (source_env_mem(P,op_input(X),Env) <=> source_space_lookup_mem(P,X,Env))).
fof(source_env_literal, axiom,
  ! [P,X,Env] : (source_env_mem(P,op_literal(X),Env) <=> literal_mem(P,X))).
fof(source_env_singleton, axiom,
  ! [P,Q,Env] : (source_env_mem(P,op_singleton(Q),Env) <=> path_env_matches(P,Q,Env))).
fof(source_env_union, axiom,
  ! [P,A,B,Env] : (source_env_mem(P,op_union(A,B),Env) <=> (source_env_mem(P,A,Env) | source_env_mem(P,B,Env)))).
fof(source_env_intersection, axiom,
  ! [P,A,B,Env] : (source_env_mem(P,op_intersection(A,B),Env) <=> (source_env_mem(P,A,Env) & source_env_mem(P,B,Env)))).
fof(source_env_diff, axiom,
  ! [P,A,B,Env] : (source_env_mem(P,op_diff(A,B),Env) <=> (source_env_mem(P,A,Env) & ~ source_env_mem(P,B,Env)))).
fof(source_env_restriction, axiom,
  ! [P,A,B,Env] : (source_env_mem(P,op_restriction(A,B),Env) <=> (source_env_mem(P,A,Env) & ? [Q] : (source_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(source_env_raffination, axiom,
  ! [P,A,B,Env] : (source_env_mem(P,op_raffination(A,B),Env) <=> (source_env_mem(P,A,Env) & ~ ? [Q] : (source_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(source_env_product, axiom,
  ! [P,A,B,Env] : (source_env_mem(P,op_product(A,B),Env) <=> ? [Q,R] : (source_env_mem(Q,A,Env) & source_env_mem(R,B,Env) & p_append(Q,R,P)))).
fof(source_env_wrap, axiom,
  ! [P,A,Q,Env] : (source_env_mem(P,op_wrap(A,Q),Env) <=> ? [Prefix,Tail] : (path_env_matches(Prefix,Q,Env) & source_env_mem(Tail,A,Env) & p_append(Prefix,Tail,P)))).
fof(source_env_unwrap, axiom,
  ! [P,A,Q,Env] : (source_env_mem(P,op_unwrap(A,Q),Env) <=> ? [Prefix,Full] : (path_env_matches(Prefix,Q,Env) & p_append(Prefix,P,Full) & source_env_mem(Full,A,Env)))).
fof(source_env_tails_union, axiom,
  ! [P,A,Env] : (source_env_mem(P,op_tails_union(A),Env) <=> ? [I] : source_env_mem(cons(I,P),A,Env))).
fof(source_env_tails_intersection, axiom,
  ! [P,A,Env] : (source_env_mem(P,op_tails_intersection(A),Env) <=> ((? [I,Q] : source_env_mem(cons(I,Q),A,Env)) & ! [I] : ((? [Q] : source_env_mem(cons(I,Q),A,Env)) => source_env_mem(cons(I,P),A,Env))))).
fof(source_env_prefix_closure, axiom,
  ! [P,A,Env] : (source_env_mem(P,op_prefix_closure(A),Env) <=> (P != nil & ? [Q] : (source_env_mem(Q,A,Env) & p_prefix(P,Q))))).
fof(source_env_suffix_closure, axiom,
  ! [P,A,Env] : (source_env_mem(P,op_suffix_closure(A),Env) <=> (P != nil & ? [Q] : (source_env_mem(Q,A,Env) & p_suffix(P,Q))))).
fof(source_env_tails_closure, axiom,
  ! [P,A,Env] : (source_env_mem(P,op_tails_closure(A),Env) <=> (((P = nil) & ? [Q] : source_env_mem(Q,A,Env)) | (P != nil & ? [Q] : (source_env_mem(Q,A,Env) & p_suffix(P,Q)))))).
fof(source_env_iter, axiom,
  ! [P,A,Sym,Rest,Body,Env] : (source_env_mem(P,op_iter(A,Sym,Rest,Body),Env) <=> ? [I] : ((? [Q] : source_env_mem(cons(I,Q),A,Env)) & source_env_mem(P,Body,env_space(Rest,op_child_env(A,I,Env),env_path(Sym,path_item(I),Env)))))).
fof(source_env_child, axiom,
  ! [P,A,I,Captured,Env] : (source_env_mem(P,op_child_env(A,I,Captured),Env) <=> source_env_mem(cons(I,P),A,Captured))).
fof(source_env_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update,Env] : (source_env_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update),Env) <=> fold_env_sem(P,A,Initial,Acc,Sym,Rest,Body,Update,Env))).
fof(source_env_fixpoint, axiom,
  ! [P,A,Var,Step,Env] : (source_env_mem(P,op_fixpoint(A,Var,Step),Env) <=> (source_env_mem(P,A,Env) | source_env_mem(P,Step,env_space(Var,op_fixpoint(A,Var,Step),Env))))).
fof(source_env_grounded_ps, axiom,
  ! [P,Q,Env] : (source_env_mem(P,op_grounded_ps(Q),Env) <=> grounded_ps_env_sem(P,Q,Env))).
fof(source_env_grounded_ss, axiom,
  ! [P,A,Env] : (source_env_mem(P,op_grounded_ss(A),Env) <=> grounded_ss_env_sem(P,A,Env))).
fof(source_env_range, axiom,
  ! [P,A,Start,End,Env] : (source_env_mem(P,op_range(A,Start,End),Env) <=> (source_env_mem(P,A,Env) & range_select_env(P,A,Env,Start,End)))).
fof(optimized_source_empty, axiom,
  ! [P] : (~ optimized_source_mem(P,op_empty))).
fof(optimized_source_input, axiom,
  ! [P,X] : (optimized_source_mem(P,op_input(X)) <=> input_mem(P,X))).
fof(optimized_source_literal, axiom,
  ! [P,X] : (optimized_source_mem(P,op_literal(X)) <=> literal_mem(P,X))).
fof(optimized_source_singleton, axiom,
  ! [P,Q] : (optimized_source_mem(P,op_singleton(Q)) <=> path_matches(P,Q))).
fof(optimized_source_union, axiom,
  ! [P,A,B] : (optimized_source_mem(P,op_union(A,B)) <=> (optimized_source_mem(P,A) | optimized_source_mem(P,B)))).
fof(optimized_source_intersection, axiom,
  ! [P,A,B] : (optimized_source_mem(P,op_intersection(A,B)) <=> (optimized_source_mem(P,A) & optimized_source_mem(P,B)))).
fof(optimized_source_diff, axiom,
  ! [P,A,B] : (optimized_source_mem(P,op_diff(A,B)) <=> (optimized_source_mem(P,A) & ~ optimized_source_mem(P,B)))).
fof(optimized_source_restriction, axiom,
  ! [P,A,B] : (optimized_source_mem(P,op_restriction(A,B)) <=> (optimized_source_mem(P,A) & ? [Q] : (optimized_source_mem(Q,B) & p_prefix(Q,P))))).
fof(optimized_source_raffination, axiom,
  ! [P,A,B] : (optimized_source_mem(P,op_raffination(A,B)) <=> (optimized_source_mem(P,A) & ~ ? [Q] : (optimized_source_mem(Q,B) & p_prefix(Q,P))))).
fof(optimized_source_product, axiom,
  ! [P,A,B] : (optimized_source_mem(P,op_product(A,B)) <=> ? [Q,R] : (optimized_source_mem(Q,A) & optimized_source_mem(R,B) & p_append(Q,R,P)))).
fof(optimized_source_wrap, axiom,
  ! [P,A,Q] : (optimized_source_mem(P,op_wrap(A,Q)) <=> ? [Prefix,Tail] : (path_matches(Prefix,Q) & optimized_source_mem(Tail,A) & p_append(Prefix,Tail,P)))).
fof(optimized_source_unwrap, axiom,
  ! [P,A,Q] : (optimized_source_mem(P,op_unwrap(A,Q)) <=> ? [Prefix,Full] : (path_matches(Prefix,Q) & p_append(Prefix,P,Full) & optimized_source_mem(Full,A)))).
fof(optimized_source_tails_union, axiom,
  ! [P,A] : (optimized_source_mem(P,op_tails_union(A)) <=> ? [I] : optimized_source_mem(cons(I,P),A))).
fof(optimized_source_tails_intersection, axiom,
  ! [P,A] : (optimized_source_mem(P,op_tails_intersection(A)) <=> ((? [I,Q] : optimized_source_mem(cons(I,Q),A)) & ! [I] : ((? [Q] : optimized_source_mem(cons(I,Q),A)) => optimized_source_mem(cons(I,P),A))))).
fof(optimized_source_prefix_closure, axiom,
  ! [P,A] : (optimized_source_mem(P,op_prefix_closure(A)) <=> (P != nil & ? [Q] : (optimized_source_mem(Q,A) & p_prefix(P,Q))))).
fof(optimized_source_suffix_closure, axiom,
  ! [P,A] : (optimized_source_mem(P,op_suffix_closure(A)) <=> (P != nil & ? [Q] : (optimized_source_mem(Q,A) & p_suffix(P,Q))))).
fof(optimized_source_tails_closure, axiom,
  ! [P,A] : (optimized_source_mem(P,op_tails_closure(A)) <=> (((P = nil) & ? [Q] : optimized_source_mem(Q,A)) | (P != nil & ? [Q] : (optimized_source_mem(Q,A) & p_suffix(P,Q)))))).
fof(optimized_source_iter, axiom,
  ! [P,A,Sym,Rest,Body] : (optimized_source_mem(P,op_iter(A,Sym,Rest,Body)) <=> optimized_source_env_mem(P,op_iter(A,Sym,Rest,Body),env_empty))).
fof(optimized_source_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (optimized_source_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> fold_sem(P,A,Initial,Acc,Sym,Rest,Body,Update))).
fof(optimized_source_fixpoint, axiom,
  ! [P,A,Var,Step] : (optimized_source_mem(P,op_fixpoint(A,Var,Step)) <=> optimized_source_env_mem(P,op_fixpoint(A,Var,Step),env_empty))).
fof(optimized_source_grounded_ps, axiom,
  ! [P,Q] : (optimized_source_mem(P,op_grounded_ps(Q)) <=> grounded_ps_sem(P,Q))).
fof(optimized_source_grounded_ss, axiom,
  ! [P,A] : (optimized_source_mem(P,op_grounded_ss(A)) <=> grounded_ss_sem(P,A))).
fof(optimized_source_range, axiom,
  ! [P,A,Start,End] : (optimized_source_mem(P,op_range(A,Start,End)) <=> optimized_source_env_mem(P,op_range(A,Start,End),env_empty))).
fof(optimized_source_space_lookup_hit, axiom,
  ! [P,X,S,Outer] : (optimized_source_space_lookup_mem(P,X,env_space(X,S,Outer)) <=> optimized_source_env_mem(P,S,Outer))).
fof(optimized_source_space_lookup_miss_space, axiom,
  ! [P,X,Other,S,Outer] : (X != Other => (optimized_source_space_lookup_mem(P,X,env_space(Other,S,Outer)) <=> optimized_source_space_lookup_mem(P,X,Outer)))).
fof(optimized_source_space_lookup_skip_path, axiom,
  ! [P,X,R,Q,Outer] : (optimized_source_space_lookup_mem(P,X,env_path(R,Q,Outer)) <=> optimized_source_space_lookup_mem(P,X,Outer))).
fof(optimized_source_space_lookup_empty, axiom,
  ! [P,X] : (optimized_source_space_lookup_mem(P,X,env_empty) <=> input_mem(P,X))).
fof(optimized_source_env_empty, axiom,
  ! [P,Env] : (~ optimized_source_env_mem(P,op_empty,Env))).
fof(optimized_source_env_input, axiom,
  ! [P,X,Env] : (optimized_source_env_mem(P,op_input(X),Env) <=> optimized_source_space_lookup_mem(P,X,Env))).
fof(optimized_source_env_literal, axiom,
  ! [P,X,Env] : (optimized_source_env_mem(P,op_literal(X),Env) <=> literal_mem(P,X))).
fof(optimized_source_env_singleton, axiom,
  ! [P,Q,Env] : (optimized_source_env_mem(P,op_singleton(Q),Env) <=> path_env_matches(P,Q,Env))).
fof(optimized_source_env_union, axiom,
  ! [P,A,B,Env] : (optimized_source_env_mem(P,op_union(A,B),Env) <=> (optimized_source_env_mem(P,A,Env) | optimized_source_env_mem(P,B,Env)))).
fof(optimized_source_env_intersection, axiom,
  ! [P,A,B,Env] : (optimized_source_env_mem(P,op_intersection(A,B),Env) <=> (optimized_source_env_mem(P,A,Env) & optimized_source_env_mem(P,B,Env)))).
fof(optimized_source_env_diff, axiom,
  ! [P,A,B,Env] : (optimized_source_env_mem(P,op_diff(A,B),Env) <=> (optimized_source_env_mem(P,A,Env) & ~ optimized_source_env_mem(P,B,Env)))).
fof(optimized_source_env_restriction, axiom,
  ! [P,A,B,Env] : (optimized_source_env_mem(P,op_restriction(A,B),Env) <=> (optimized_source_env_mem(P,A,Env) & ? [Q] : (optimized_source_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(optimized_source_env_raffination, axiom,
  ! [P,A,B,Env] : (optimized_source_env_mem(P,op_raffination(A,B),Env) <=> (optimized_source_env_mem(P,A,Env) & ~ ? [Q] : (optimized_source_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(optimized_source_env_product, axiom,
  ! [P,A,B,Env] : (optimized_source_env_mem(P,op_product(A,B),Env) <=> ? [Q,R] : (optimized_source_env_mem(Q,A,Env) & optimized_source_env_mem(R,B,Env) & p_append(Q,R,P)))).
fof(optimized_source_env_wrap, axiom,
  ! [P,A,Q,Env] : (optimized_source_env_mem(P,op_wrap(A,Q),Env) <=> ? [Prefix,Tail] : (path_env_matches(Prefix,Q,Env) & optimized_source_env_mem(Tail,A,Env) & p_append(Prefix,Tail,P)))).
fof(optimized_source_env_unwrap, axiom,
  ! [P,A,Q,Env] : (optimized_source_env_mem(P,op_unwrap(A,Q),Env) <=> ? [Prefix,Full] : (path_env_matches(Prefix,Q,Env) & p_append(Prefix,P,Full) & optimized_source_env_mem(Full,A,Env)))).
fof(optimized_source_env_tails_union, axiom,
  ! [P,A,Env] : (optimized_source_env_mem(P,op_tails_union(A),Env) <=> ? [I] : optimized_source_env_mem(cons(I,P),A,Env))).
fof(optimized_source_env_tails_intersection, axiom,
  ! [P,A,Env] : (optimized_source_env_mem(P,op_tails_intersection(A),Env) <=> ((? [I,Q] : optimized_source_env_mem(cons(I,Q),A,Env)) & ! [I] : ((? [Q] : optimized_source_env_mem(cons(I,Q),A,Env)) => optimized_source_env_mem(cons(I,P),A,Env))))).
fof(optimized_source_env_prefix_closure, axiom,
  ! [P,A,Env] : (optimized_source_env_mem(P,op_prefix_closure(A),Env) <=> (P != nil & ? [Q] : (optimized_source_env_mem(Q,A,Env) & p_prefix(P,Q))))).
fof(optimized_source_env_suffix_closure, axiom,
  ! [P,A,Env] : (optimized_source_env_mem(P,op_suffix_closure(A),Env) <=> (P != nil & ? [Q] : (optimized_source_env_mem(Q,A,Env) & p_suffix(P,Q))))).
fof(optimized_source_env_tails_closure, axiom,
  ! [P,A,Env] : (optimized_source_env_mem(P,op_tails_closure(A),Env) <=> (((P = nil) & ? [Q] : optimized_source_env_mem(Q,A,Env)) | (P != nil & ? [Q] : (optimized_source_env_mem(Q,A,Env) & p_suffix(P,Q)))))).
fof(optimized_source_env_iter, axiom,
  ! [P,A,Sym,Rest,Body,Env] : (optimized_source_env_mem(P,op_iter(A,Sym,Rest,Body),Env) <=> ? [I] : ((? [Q] : optimized_source_env_mem(cons(I,Q),A,Env)) & optimized_source_env_mem(P,Body,env_space(Rest,op_child_env(A,I,Env),env_path(Sym,path_item(I),Env)))))).
fof(optimized_source_env_child, axiom,
  ! [P,A,I,Captured,Env] : (optimized_source_env_mem(P,op_child_env(A,I,Captured),Env) <=> optimized_source_env_mem(cons(I,P),A,Captured))).
fof(optimized_source_env_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update,Env] : (optimized_source_env_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update),Env) <=> fold_env_sem(P,A,Initial,Acc,Sym,Rest,Body,Update,Env))).
fof(optimized_source_env_fixpoint, axiom,
  ! [P,A,Var,Step,Env] : (optimized_source_env_mem(P,op_fixpoint(A,Var,Step),Env) <=> (optimized_source_env_mem(P,A,Env) | optimized_source_env_mem(P,Step,env_space(Var,op_fixpoint(A,Var,Step),Env))))).
fof(optimized_source_env_grounded_ps, axiom,
  ! [P,Q,Env] : (optimized_source_env_mem(P,op_grounded_ps(Q),Env) <=> grounded_ps_env_sem(P,Q,Env))).
fof(optimized_source_env_grounded_ss, axiom,
  ! [P,A,Env] : (optimized_source_env_mem(P,op_grounded_ss(A),Env) <=> grounded_ss_env_sem(P,A,Env))).
fof(optimized_source_env_range, axiom,
  ! [P,A,Start,End,Env] : (optimized_source_env_mem(P,op_range(A,Start,End),Env) <=> (optimized_source_env_mem(P,A,Env) & range_select_env(P,A,Env,Start,End)))).
fof(trie_empty, axiom,
  ! [P] : (~ trie_mem(P,op_empty))).
fof(trie_input, axiom,
  ! [P,X] : (trie_mem(P,op_input(X)) <=> input_mem(P,X))).
fof(trie_literal, axiom,
  ! [P,X] : (trie_mem(P,op_literal(X)) <=> literal_mem(P,X))).
fof(trie_singleton, axiom,
  ! [P,Q] : (trie_mem(P,op_singleton(Q)) <=> path_matches(P,Q))).
fof(trie_union, axiom,
  ! [P,A,B] : (trie_mem(P,op_union(A,B)) <=> (trie_mem(P,A) | trie_mem(P,B)))).
fof(trie_intersection, axiom,
  ! [P,A,B] : (trie_mem(P,op_intersection(A,B)) <=> (trie_mem(P,A) & trie_mem(P,B)))).
fof(trie_diff, axiom,
  ! [P,A,B] : (trie_mem(P,op_diff(A,B)) <=> (trie_mem(P,A) & ~ trie_mem(P,B)))).
fof(trie_restriction, axiom,
  ! [P,A,B] : (trie_mem(P,op_restriction(A,B)) <=> (trie_mem(P,A) & ? [Q] : (trie_mem(Q,B) & p_prefix(Q,P))))).
fof(trie_raffination, axiom,
  ! [P,A,B] : (trie_mem(P,op_raffination(A,B)) <=> (trie_mem(P,A) & ~ ? [Q] : (trie_mem(Q,B) & p_prefix(Q,P))))).
fof(trie_product, axiom,
  ! [P,A,B] : (trie_mem(P,op_product(A,B)) <=> ? [Q,R] : (trie_mem(Q,A) & trie_mem(R,B) & p_append(Q,R,P)))).
fof(trie_wrap, axiom,
  ! [P,A,Q] : (trie_mem(P,op_wrap(A,Q)) <=> ? [Prefix,Tail] : (path_matches(Prefix,Q) & trie_mem(Tail,A) & p_append(Prefix,Tail,P)))).
fof(trie_unwrap, axiom,
  ! [P,A,Q] : (trie_mem(P,op_unwrap(A,Q)) <=> ? [Prefix,Full] : (path_matches(Prefix,Q) & p_append(Prefix,P,Full) & trie_mem(Full,A)))).
fof(trie_tails_union, axiom,
  ! [P,A] : (trie_mem(P,op_tails_union(A)) <=> ? [I] : trie_mem(cons(I,P),A))).
fof(trie_tails_intersection, axiom,
  ! [P,A] : (trie_mem(P,op_tails_intersection(A)) <=> ((? [I,Q] : trie_mem(cons(I,Q),A)) & ! [I] : ((? [Q] : trie_mem(cons(I,Q),A)) => trie_mem(cons(I,P),A))))).
fof(trie_prefix_closure, axiom,
  ! [P,A] : (trie_mem(P,op_prefix_closure(A)) <=> (P != nil & ? [Q] : (trie_mem(Q,A) & p_prefix(P,Q))))).
fof(trie_suffix_closure, axiom,
  ! [P,A] : (trie_mem(P,op_suffix_closure(A)) <=> (P != nil & ? [Q] : (trie_mem(Q,A) & p_suffix(P,Q))))).
fof(trie_tails_closure, axiom,
  ! [P,A] : (trie_mem(P,op_tails_closure(A)) <=> (((P = nil) & ? [Q] : trie_mem(Q,A)) | (P != nil & ? [Q] : (trie_mem(Q,A) & p_suffix(P,Q)))))).
fof(trie_iter, axiom,
  ! [P,A,Sym,Rest,Body] : (trie_mem(P,op_iter(A,Sym,Rest,Body)) <=> trie_env_mem(P,op_iter(A,Sym,Rest,Body),env_empty))).
fof(trie_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (trie_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> fold_sem(P,A,Initial,Acc,Sym,Rest,Body,Update))).
fof(trie_fixpoint, axiom,
  ! [P,A,Var,Step] : (trie_mem(P,op_fixpoint(A,Var,Step)) <=> trie_env_mem(P,op_fixpoint(A,Var,Step),env_empty))).
fof(trie_grounded_ps, axiom,
  ! [P,Q] : (trie_mem(P,op_grounded_ps(Q)) <=> grounded_ps_sem(P,Q))).
fof(trie_grounded_ss, axiom,
  ! [P,A] : (trie_mem(P,op_grounded_ss(A)) <=> grounded_ss_sem(P,A))).
fof(trie_range, axiom,
  ! [P,A,Start,End] : (trie_mem(P,op_range(A,Start,End)) <=> trie_env_mem(P,op_range(A,Start,End),env_empty))).
fof(trie_space_lookup_hit, axiom,
  ! [P,X,S,Outer] : (trie_space_lookup_mem(P,X,env_space(X,S,Outer)) <=> trie_env_mem(P,S,Outer))).
fof(trie_space_lookup_miss_space, axiom,
  ! [P,X,Other,S,Outer] : (X != Other => (trie_space_lookup_mem(P,X,env_space(Other,S,Outer)) <=> trie_space_lookup_mem(P,X,Outer)))).
fof(trie_space_lookup_skip_path, axiom,
  ! [P,X,R,Q,Outer] : (trie_space_lookup_mem(P,X,env_path(R,Q,Outer)) <=> trie_space_lookup_mem(P,X,Outer))).
fof(trie_space_lookup_empty, axiom,
  ! [P,X] : (trie_space_lookup_mem(P,X,env_empty) <=> input_mem(P,X))).
fof(trie_env_empty, axiom,
  ! [P,Env] : (~ trie_env_mem(P,op_empty,Env))).
fof(trie_env_input, axiom,
  ! [P,X,Env] : (trie_env_mem(P,op_input(X),Env) <=> trie_space_lookup_mem(P,X,Env))).
fof(trie_env_literal, axiom,
  ! [P,X,Env] : (trie_env_mem(P,op_literal(X),Env) <=> literal_mem(P,X))).
fof(trie_env_singleton, axiom,
  ! [P,Q,Env] : (trie_env_mem(P,op_singleton(Q),Env) <=> path_env_matches(P,Q,Env))).
fof(trie_env_union, axiom,
  ! [P,A,B,Env] : (trie_env_mem(P,op_union(A,B),Env) <=> (trie_env_mem(P,A,Env) | trie_env_mem(P,B,Env)))).
fof(trie_env_intersection, axiom,
  ! [P,A,B,Env] : (trie_env_mem(P,op_intersection(A,B),Env) <=> (trie_env_mem(P,A,Env) & trie_env_mem(P,B,Env)))).
fof(trie_env_diff, axiom,
  ! [P,A,B,Env] : (trie_env_mem(P,op_diff(A,B),Env) <=> (trie_env_mem(P,A,Env) & ~ trie_env_mem(P,B,Env)))).
fof(trie_env_restriction, axiom,
  ! [P,A,B,Env] : (trie_env_mem(P,op_restriction(A,B),Env) <=> (trie_env_mem(P,A,Env) & ? [Q] : (trie_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(trie_env_raffination, axiom,
  ! [P,A,B,Env] : (trie_env_mem(P,op_raffination(A,B),Env) <=> (trie_env_mem(P,A,Env) & ~ ? [Q] : (trie_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(trie_env_product, axiom,
  ! [P,A,B,Env] : (trie_env_mem(P,op_product(A,B),Env) <=> ? [Q,R] : (trie_env_mem(Q,A,Env) & trie_env_mem(R,B,Env) & p_append(Q,R,P)))).
fof(trie_env_wrap, axiom,
  ! [P,A,Q,Env] : (trie_env_mem(P,op_wrap(A,Q),Env) <=> ? [Prefix,Tail] : (path_env_matches(Prefix,Q,Env) & trie_env_mem(Tail,A,Env) & p_append(Prefix,Tail,P)))).
fof(trie_env_unwrap, axiom,
  ! [P,A,Q,Env] : (trie_env_mem(P,op_unwrap(A,Q),Env) <=> ? [Prefix,Full] : (path_env_matches(Prefix,Q,Env) & p_append(Prefix,P,Full) & trie_env_mem(Full,A,Env)))).
fof(trie_env_tails_union, axiom,
  ! [P,A,Env] : (trie_env_mem(P,op_tails_union(A),Env) <=> ? [I] : trie_env_mem(cons(I,P),A,Env))).
fof(trie_env_tails_intersection, axiom,
  ! [P,A,Env] : (trie_env_mem(P,op_tails_intersection(A),Env) <=> ((? [I,Q] : trie_env_mem(cons(I,Q),A,Env)) & ! [I] : ((? [Q] : trie_env_mem(cons(I,Q),A,Env)) => trie_env_mem(cons(I,P),A,Env))))).
fof(trie_env_prefix_closure, axiom,
  ! [P,A,Env] : (trie_env_mem(P,op_prefix_closure(A),Env) <=> (P != nil & ? [Q] : (trie_env_mem(Q,A,Env) & p_prefix(P,Q))))).
fof(trie_env_suffix_closure, axiom,
  ! [P,A,Env] : (trie_env_mem(P,op_suffix_closure(A),Env) <=> (P != nil & ? [Q] : (trie_env_mem(Q,A,Env) & p_suffix(P,Q))))).
fof(trie_env_tails_closure, axiom,
  ! [P,A,Env] : (trie_env_mem(P,op_tails_closure(A),Env) <=> (((P = nil) & ? [Q] : trie_env_mem(Q,A,Env)) | (P != nil & ? [Q] : (trie_env_mem(Q,A,Env) & p_suffix(P,Q)))))).
fof(trie_env_iter, axiom,
  ! [P,A,Sym,Rest,Body,Env] : (trie_env_mem(P,op_iter(A,Sym,Rest,Body),Env) <=> ? [I] : ((? [Q] : trie_env_mem(cons(I,Q),A,Env)) & trie_env_mem(P,Body,env_space(Rest,op_child_env(A,I,Env),env_path(Sym,path_item(I),Env)))))).
fof(trie_env_child, axiom,
  ! [P,A,I,Captured,Env] : (trie_env_mem(P,op_child_env(A,I,Captured),Env) <=> trie_env_mem(cons(I,P),A,Captured))).
fof(trie_env_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update,Env] : (trie_env_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update),Env) <=> fold_env_sem(P,A,Initial,Acc,Sym,Rest,Body,Update,Env))).
fof(trie_env_fixpoint, axiom,
  ! [P,A,Var,Step,Env] : (trie_env_mem(P,op_fixpoint(A,Var,Step),Env) <=> (trie_env_mem(P,A,Env) | trie_env_mem(P,Step,env_space(Var,op_fixpoint(A,Var,Step),Env))))).
fof(trie_env_grounded_ps, axiom,
  ! [P,Q,Env] : (trie_env_mem(P,op_grounded_ps(Q),Env) <=> grounded_ps_env_sem(P,Q,Env))).
fof(trie_env_grounded_ss, axiom,
  ! [P,A,Env] : (trie_env_mem(P,op_grounded_ss(A),Env) <=> grounded_ss_env_sem(P,A,Env))).
fof(trie_env_range, axiom,
  ! [P,A,Start,End,Env] : (trie_env_mem(P,op_range(A,Start,End),Env) <=> (trie_env_mem(P,A,Env) & range_select_env(P,A,Env,Start,End)))).
fof(zipper_empty, axiom,
  ! [P] : (~ zipper_mem(P,op_empty))).
fof(zipper_input, axiom,
  ! [P,X] : (zipper_mem(P,op_input(X)) <=> input_mem(P,X))).
fof(zipper_literal, axiom,
  ! [P,X] : (zipper_mem(P,op_literal(X)) <=> literal_mem(P,X))).
fof(zipper_singleton, axiom,
  ! [P,Q] : (zipper_mem(P,op_singleton(Q)) <=> path_matches(P,Q))).
fof(zipper_union, axiom,
  ! [P,A,B] : (zipper_mem(P,op_union(A,B)) <=> (zipper_mem(P,A) | zipper_mem(P,B)))).
fof(zipper_intersection, axiom,
  ! [P,A,B] : (zipper_mem(P,op_intersection(A,B)) <=> (zipper_mem(P,A) & zipper_mem(P,B)))).
fof(zipper_diff, axiom,
  ! [P,A,B] : (zipper_mem(P,op_diff(A,B)) <=> (zipper_mem(P,A) & ~ zipper_mem(P,B)))).
fof(zipper_restriction, axiom,
  ! [P,A,B] : (zipper_mem(P,op_restriction(A,B)) <=> (zipper_mem(P,A) & ? [Q] : (zipper_mem(Q,B) & p_prefix(Q,P))))).
fof(zipper_raffination, axiom,
  ! [P,A,B] : (zipper_mem(P,op_raffination(A,B)) <=> (zipper_mem(P,A) & ~ ? [Q] : (zipper_mem(Q,B) & p_prefix(Q,P))))).
fof(zipper_product, axiom,
  ! [P,A,B] : (zipper_mem(P,op_product(A,B)) <=> ? [Q,R] : (zipper_mem(Q,A) & zipper_mem(R,B) & p_append(Q,R,P)))).
fof(zipper_wrap, axiom,
  ! [P,A,Q] : (zipper_mem(P,op_wrap(A,Q)) <=> ? [Prefix,Tail] : (path_matches(Prefix,Q) & zipper_mem(Tail,A) & p_append(Prefix,Tail,P)))).
fof(zipper_unwrap, axiom,
  ! [P,A,Q] : (zipper_mem(P,op_unwrap(A,Q)) <=> ? [Prefix,Full] : (path_matches(Prefix,Q) & p_append(Prefix,P,Full) & zipper_mem(Full,A)))).
fof(zipper_tails_union, axiom,
  ! [P,A] : (zipper_mem(P,op_tails_union(A)) <=> ? [I] : zipper_mem(cons(I,P),A))).
fof(zipper_tails_intersection, axiom,
  ! [P,A] : (zipper_mem(P,op_tails_intersection(A)) <=> ((? [I,Q] : zipper_mem(cons(I,Q),A)) & ! [I] : ((? [Q] : zipper_mem(cons(I,Q),A)) => zipper_mem(cons(I,P),A))))).
fof(zipper_prefix_closure, axiom,
  ! [P,A] : (zipper_mem(P,op_prefix_closure(A)) <=> (P != nil & ? [Q] : (zipper_mem(Q,A) & p_prefix(P,Q))))).
fof(zipper_suffix_closure, axiom,
  ! [P,A] : (zipper_mem(P,op_suffix_closure(A)) <=> (P != nil & ? [Q] : (zipper_mem(Q,A) & p_suffix(P,Q))))).
fof(zipper_tails_closure, axiom,
  ! [P,A] : (zipper_mem(P,op_tails_closure(A)) <=> (((P = nil) & ? [Q] : zipper_mem(Q,A)) | (P != nil & ? [Q] : (zipper_mem(Q,A) & p_suffix(P,Q)))))).
fof(zipper_iter, axiom,
  ! [P,A,Sym,Rest,Body] : (zipper_mem(P,op_iter(A,Sym,Rest,Body)) <=> zipper_env_mem(P,op_iter(A,Sym,Rest,Body),env_empty))).
fof(zipper_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (zipper_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> fold_sem(P,A,Initial,Acc,Sym,Rest,Body,Update))).
fof(zipper_fixpoint, axiom,
  ! [P,A,Var,Step] : (zipper_mem(P,op_fixpoint(A,Var,Step)) <=> zipper_env_mem(P,op_fixpoint(A,Var,Step),env_empty))).
fof(zipper_grounded_ps, axiom,
  ! [P,Q] : (zipper_mem(P,op_grounded_ps(Q)) <=> grounded_ps_sem(P,Q))).
fof(zipper_grounded_ss, axiom,
  ! [P,A] : (zipper_mem(P,op_grounded_ss(A)) <=> grounded_ss_sem(P,A))).
fof(zipper_range, axiom,
  ! [P,A,Start,End] : (zipper_mem(P,op_range(A,Start,End)) <=> zipper_env_mem(P,op_range(A,Start,End),env_empty))).
fof(zipper_space_lookup_hit, axiom,
  ! [P,X,S,Outer] : (zipper_space_lookup_mem(P,X,env_space(X,S,Outer)) <=> zipper_env_mem(P,S,Outer))).
fof(zipper_space_lookup_miss_space, axiom,
  ! [P,X,Other,S,Outer] : (X != Other => (zipper_space_lookup_mem(P,X,env_space(Other,S,Outer)) <=> zipper_space_lookup_mem(P,X,Outer)))).
fof(zipper_space_lookup_skip_path, axiom,
  ! [P,X,R,Q,Outer] : (zipper_space_lookup_mem(P,X,env_path(R,Q,Outer)) <=> zipper_space_lookup_mem(P,X,Outer))).
fof(zipper_space_lookup_empty, axiom,
  ! [P,X] : (zipper_space_lookup_mem(P,X,env_empty) <=> input_mem(P,X))).
fof(zipper_env_empty, axiom,
  ! [P,Env] : (~ zipper_env_mem(P,op_empty,Env))).
fof(zipper_env_input, axiom,
  ! [P,X,Env] : (zipper_env_mem(P,op_input(X),Env) <=> zipper_space_lookup_mem(P,X,Env))).
fof(zipper_env_literal, axiom,
  ! [P,X,Env] : (zipper_env_mem(P,op_literal(X),Env) <=> literal_mem(P,X))).
fof(zipper_env_singleton, axiom,
  ! [P,Q,Env] : (zipper_env_mem(P,op_singleton(Q),Env) <=> path_env_matches(P,Q,Env))).
fof(zipper_env_union, axiom,
  ! [P,A,B,Env] : (zipper_env_mem(P,op_union(A,B),Env) <=> (zipper_env_mem(P,A,Env) | zipper_env_mem(P,B,Env)))).
fof(zipper_env_intersection, axiom,
  ! [P,A,B,Env] : (zipper_env_mem(P,op_intersection(A,B),Env) <=> (zipper_env_mem(P,A,Env) & zipper_env_mem(P,B,Env)))).
fof(zipper_env_diff, axiom,
  ! [P,A,B,Env] : (zipper_env_mem(P,op_diff(A,B),Env) <=> (zipper_env_mem(P,A,Env) & ~ zipper_env_mem(P,B,Env)))).
fof(zipper_env_restriction, axiom,
  ! [P,A,B,Env] : (zipper_env_mem(P,op_restriction(A,B),Env) <=> (zipper_env_mem(P,A,Env) & ? [Q] : (zipper_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(zipper_env_raffination, axiom,
  ! [P,A,B,Env] : (zipper_env_mem(P,op_raffination(A,B),Env) <=> (zipper_env_mem(P,A,Env) & ~ ? [Q] : (zipper_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(zipper_env_product, axiom,
  ! [P,A,B,Env] : (zipper_env_mem(P,op_product(A,B),Env) <=> ? [Q,R] : (zipper_env_mem(Q,A,Env) & zipper_env_mem(R,B,Env) & p_append(Q,R,P)))).
fof(zipper_env_wrap, axiom,
  ! [P,A,Q,Env] : (zipper_env_mem(P,op_wrap(A,Q),Env) <=> ? [Prefix,Tail] : (path_env_matches(Prefix,Q,Env) & zipper_env_mem(Tail,A,Env) & p_append(Prefix,Tail,P)))).
fof(zipper_env_unwrap, axiom,
  ! [P,A,Q,Env] : (zipper_env_mem(P,op_unwrap(A,Q),Env) <=> ? [Prefix,Full] : (path_env_matches(Prefix,Q,Env) & p_append(Prefix,P,Full) & zipper_env_mem(Full,A,Env)))).
fof(zipper_env_tails_union, axiom,
  ! [P,A,Env] : (zipper_env_mem(P,op_tails_union(A),Env) <=> ? [I] : zipper_env_mem(cons(I,P),A,Env))).
fof(zipper_env_tails_intersection, axiom,
  ! [P,A,Env] : (zipper_env_mem(P,op_tails_intersection(A),Env) <=> ((? [I,Q] : zipper_env_mem(cons(I,Q),A,Env)) & ! [I] : ((? [Q] : zipper_env_mem(cons(I,Q),A,Env)) => zipper_env_mem(cons(I,P),A,Env))))).
fof(zipper_env_prefix_closure, axiom,
  ! [P,A,Env] : (zipper_env_mem(P,op_prefix_closure(A),Env) <=> (P != nil & ? [Q] : (zipper_env_mem(Q,A,Env) & p_prefix(P,Q))))).
fof(zipper_env_suffix_closure, axiom,
  ! [P,A,Env] : (zipper_env_mem(P,op_suffix_closure(A),Env) <=> (P != nil & ? [Q] : (zipper_env_mem(Q,A,Env) & p_suffix(P,Q))))).
fof(zipper_env_tails_closure, axiom,
  ! [P,A,Env] : (zipper_env_mem(P,op_tails_closure(A),Env) <=> (((P = nil) & ? [Q] : zipper_env_mem(Q,A,Env)) | (P != nil & ? [Q] : (zipper_env_mem(Q,A,Env) & p_suffix(P,Q)))))).
fof(zipper_env_iter, axiom,
  ! [P,A,Sym,Rest,Body,Env] : (zipper_env_mem(P,op_iter(A,Sym,Rest,Body),Env) <=> ? [I] : ((? [Q] : zipper_env_mem(cons(I,Q),A,Env)) & zipper_env_mem(P,Body,env_space(Rest,op_child_env(A,I,Env),env_path(Sym,path_item(I),Env)))))).
fof(zipper_env_child, axiom,
  ! [P,A,I,Captured,Env] : (zipper_env_mem(P,op_child_env(A,I,Captured),Env) <=> zipper_env_mem(cons(I,P),A,Captured))).
fof(zipper_env_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update,Env] : (zipper_env_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update),Env) <=> fold_env_sem(P,A,Initial,Acc,Sym,Rest,Body,Update,Env))).
fof(zipper_env_fixpoint, axiom,
  ! [P,A,Var,Step,Env] : (zipper_env_mem(P,op_fixpoint(A,Var,Step),Env) <=> (zipper_env_mem(P,A,Env) | zipper_env_mem(P,Step,env_space(Var,op_fixpoint(A,Var,Step),Env))))).
fof(zipper_env_grounded_ps, axiom,
  ! [P,Q,Env] : (zipper_env_mem(P,op_grounded_ps(Q),Env) <=> grounded_ps_env_sem(P,Q,Env))).
fof(zipper_env_grounded_ss, axiom,
  ! [P,A,Env] : (zipper_env_mem(P,op_grounded_ss(A),Env) <=> grounded_ss_env_sem(P,A,Env))).
fof(zipper_env_range, axiom,
  ! [P,A,Start,End,Env] : (zipper_env_mem(P,op_range(A,Start,End),Env) <=> (zipper_env_mem(P,A,Env) & range_select_env(P,A,Env,Start,End)))).
fof(graph_empty, axiom,
  ! [P] : (~ graph_mem(P,op_empty))).
fof(graph_input, axiom,
  ! [P,X] : (graph_mem(P,op_input(X)) <=> input_mem(P,X))).
fof(graph_literal, axiom,
  ! [P,X] : (graph_mem(P,op_literal(X)) <=> literal_mem(P,X))).
fof(graph_singleton, axiom,
  ! [P,Q] : (graph_mem(P,op_singleton(Q)) <=> path_matches(P,Q))).
fof(graph_union, axiom,
  ! [P,A,B] : (graph_mem(P,op_union(A,B)) <=> (graph_mem(P,A) | graph_mem(P,B)))).
fof(graph_intersection, axiom,
  ! [P,A,B] : (graph_mem(P,op_intersection(A,B)) <=> (graph_mem(P,A) & graph_mem(P,B)))).
fof(graph_diff, axiom,
  ! [P,A,B] : (graph_mem(P,op_diff(A,B)) <=> (graph_mem(P,A) & ~ graph_mem(P,B)))).
fof(graph_restriction, axiom,
  ! [P,A,B] : (graph_mem(P,op_restriction(A,B)) <=> (graph_mem(P,A) & ? [Q] : (graph_mem(Q,B) & p_prefix(Q,P))))).
fof(graph_raffination, axiom,
  ! [P,A,B] : (graph_mem(P,op_raffination(A,B)) <=> (graph_mem(P,A) & ~ ? [Q] : (graph_mem(Q,B) & p_prefix(Q,P))))).
fof(graph_product, axiom,
  ! [P,A,B] : (graph_mem(P,op_product(A,B)) <=> ? [Q,R] : (graph_mem(Q,A) & graph_mem(R,B) & p_append(Q,R,P)))).
fof(graph_wrap, axiom,
  ! [P,A,Q] : (graph_mem(P,op_wrap(A,Q)) <=> ? [Prefix,Tail] : (path_matches(Prefix,Q) & graph_mem(Tail,A) & p_append(Prefix,Tail,P)))).
fof(graph_unwrap, axiom,
  ! [P,A,Q] : (graph_mem(P,op_unwrap(A,Q)) <=> ? [Prefix,Full] : (path_matches(Prefix,Q) & p_append(Prefix,P,Full) & graph_mem(Full,A)))).
fof(graph_tails_union, axiom,
  ! [P,A] : (graph_mem(P,op_tails_union(A)) <=> ? [I] : graph_mem(cons(I,P),A))).
fof(graph_tails_intersection, axiom,
  ! [P,A] : (graph_mem(P,op_tails_intersection(A)) <=> ((? [I,Q] : graph_mem(cons(I,Q),A)) & ! [I] : ((? [Q] : graph_mem(cons(I,Q),A)) => graph_mem(cons(I,P),A))))).
fof(graph_prefix_closure, axiom,
  ! [P,A] : (graph_mem(P,op_prefix_closure(A)) <=> (P != nil & ? [Q] : (graph_mem(Q,A) & p_prefix(P,Q))))).
fof(graph_suffix_closure, axiom,
  ! [P,A] : (graph_mem(P,op_suffix_closure(A)) <=> (P != nil & ? [Q] : (graph_mem(Q,A) & p_suffix(P,Q))))).
fof(graph_tails_closure, axiom,
  ! [P,A] : (graph_mem(P,op_tails_closure(A)) <=> (((P = nil) & ? [Q] : graph_mem(Q,A)) | (P != nil & ? [Q] : (graph_mem(Q,A) & p_suffix(P,Q)))))).
fof(graph_iter, axiom,
  ! [P,A,Sym,Rest,Body] : (graph_mem(P,op_iter(A,Sym,Rest,Body)) <=> graph_env_mem(P,op_iter(A,Sym,Rest,Body),env_empty))).
fof(graph_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (graph_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> fold_sem(P,A,Initial,Acc,Sym,Rest,Body,Update))).
fof(graph_fixpoint, axiom,
  ! [P,A,Var,Step] : (graph_mem(P,op_fixpoint(A,Var,Step)) <=> graph_env_mem(P,op_fixpoint(A,Var,Step),env_empty))).
fof(graph_grounded_ps, axiom,
  ! [P,Q] : (graph_mem(P,op_grounded_ps(Q)) <=> grounded_ps_sem(P,Q))).
fof(graph_grounded_ss, axiom,
  ! [P,A] : (graph_mem(P,op_grounded_ss(A)) <=> grounded_ss_sem(P,A))).
fof(graph_range, axiom,
  ! [P,A,Start,End] : (graph_mem(P,op_range(A,Start,End)) <=> graph_env_mem(P,op_range(A,Start,End),env_empty))).
fof(graph_space_lookup_hit, axiom,
  ! [P,X,S,Outer] : (graph_space_lookup_mem(P,X,env_space(X,S,Outer)) <=> graph_env_mem(P,S,Outer))).
fof(graph_space_lookup_miss_space, axiom,
  ! [P,X,Other,S,Outer] : (X != Other => (graph_space_lookup_mem(P,X,env_space(Other,S,Outer)) <=> graph_space_lookup_mem(P,X,Outer)))).
fof(graph_space_lookup_skip_path, axiom,
  ! [P,X,R,Q,Outer] : (graph_space_lookup_mem(P,X,env_path(R,Q,Outer)) <=> graph_space_lookup_mem(P,X,Outer))).
fof(graph_space_lookup_empty, axiom,
  ! [P,X] : (graph_space_lookup_mem(P,X,env_empty) <=> input_mem(P,X))).
fof(graph_env_empty, axiom,
  ! [P,Env] : (~ graph_env_mem(P,op_empty,Env))).
fof(graph_env_input, axiom,
  ! [P,X,Env] : (graph_env_mem(P,op_input(X),Env) <=> graph_space_lookup_mem(P,X,Env))).
fof(graph_env_literal, axiom,
  ! [P,X,Env] : (graph_env_mem(P,op_literal(X),Env) <=> literal_mem(P,X))).
fof(graph_env_singleton, axiom,
  ! [P,Q,Env] : (graph_env_mem(P,op_singleton(Q),Env) <=> path_env_matches(P,Q,Env))).
fof(graph_env_union, axiom,
  ! [P,A,B,Env] : (graph_env_mem(P,op_union(A,B),Env) <=> (graph_env_mem(P,A,Env) | graph_env_mem(P,B,Env)))).
fof(graph_env_intersection, axiom,
  ! [P,A,B,Env] : (graph_env_mem(P,op_intersection(A,B),Env) <=> (graph_env_mem(P,A,Env) & graph_env_mem(P,B,Env)))).
fof(graph_env_diff, axiom,
  ! [P,A,B,Env] : (graph_env_mem(P,op_diff(A,B),Env) <=> (graph_env_mem(P,A,Env) & ~ graph_env_mem(P,B,Env)))).
fof(graph_env_restriction, axiom,
  ! [P,A,B,Env] : (graph_env_mem(P,op_restriction(A,B),Env) <=> (graph_env_mem(P,A,Env) & ? [Q] : (graph_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(graph_env_raffination, axiom,
  ! [P,A,B,Env] : (graph_env_mem(P,op_raffination(A,B),Env) <=> (graph_env_mem(P,A,Env) & ~ ? [Q] : (graph_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(graph_env_product, axiom,
  ! [P,A,B,Env] : (graph_env_mem(P,op_product(A,B),Env) <=> ? [Q,R] : (graph_env_mem(Q,A,Env) & graph_env_mem(R,B,Env) & p_append(Q,R,P)))).
fof(graph_env_wrap, axiom,
  ! [P,A,Q,Env] : (graph_env_mem(P,op_wrap(A,Q),Env) <=> ? [Prefix,Tail] : (path_env_matches(Prefix,Q,Env) & graph_env_mem(Tail,A,Env) & p_append(Prefix,Tail,P)))).
fof(graph_env_unwrap, axiom,
  ! [P,A,Q,Env] : (graph_env_mem(P,op_unwrap(A,Q),Env) <=> ? [Prefix,Full] : (path_env_matches(Prefix,Q,Env) & p_append(Prefix,P,Full) & graph_env_mem(Full,A,Env)))).
fof(graph_env_tails_union, axiom,
  ! [P,A,Env] : (graph_env_mem(P,op_tails_union(A),Env) <=> ? [I] : graph_env_mem(cons(I,P),A,Env))).
fof(graph_env_tails_intersection, axiom,
  ! [P,A,Env] : (graph_env_mem(P,op_tails_intersection(A),Env) <=> ((? [I,Q] : graph_env_mem(cons(I,Q),A,Env)) & ! [I] : ((? [Q] : graph_env_mem(cons(I,Q),A,Env)) => graph_env_mem(cons(I,P),A,Env))))).
fof(graph_env_prefix_closure, axiom,
  ! [P,A,Env] : (graph_env_mem(P,op_prefix_closure(A),Env) <=> (P != nil & ? [Q] : (graph_env_mem(Q,A,Env) & p_prefix(P,Q))))).
fof(graph_env_suffix_closure, axiom,
  ! [P,A,Env] : (graph_env_mem(P,op_suffix_closure(A),Env) <=> (P != nil & ? [Q] : (graph_env_mem(Q,A,Env) & p_suffix(P,Q))))).
fof(graph_env_tails_closure, axiom,
  ! [P,A,Env] : (graph_env_mem(P,op_tails_closure(A),Env) <=> (((P = nil) & ? [Q] : graph_env_mem(Q,A,Env)) | (P != nil & ? [Q] : (graph_env_mem(Q,A,Env) & p_suffix(P,Q)))))).
fof(graph_env_iter, axiom,
  ! [P,A,Sym,Rest,Body,Env] : (graph_env_mem(P,op_iter(A,Sym,Rest,Body),Env) <=> ? [I] : ((? [Q] : graph_env_mem(cons(I,Q),A,Env)) & graph_env_mem(P,Body,env_space(Rest,op_child_env(A,I,Env),env_path(Sym,path_item(I),Env)))))).
fof(graph_env_child, axiom,
  ! [P,A,I,Captured,Env] : (graph_env_mem(P,op_child_env(A,I,Captured),Env) <=> graph_env_mem(cons(I,P),A,Captured))).
fof(graph_env_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update,Env] : (graph_env_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update),Env) <=> fold_env_sem(P,A,Initial,Acc,Sym,Rest,Body,Update,Env))).
fof(graph_env_fixpoint, axiom,
  ! [P,A,Var,Step,Env] : (graph_env_mem(P,op_fixpoint(A,Var,Step),Env) <=> (graph_env_mem(P,A,Env) | graph_env_mem(P,Step,env_space(Var,op_fixpoint(A,Var,Step),Env))))).
fof(graph_env_grounded_ps, axiom,
  ! [P,Q,Env] : (graph_env_mem(P,op_grounded_ps(Q),Env) <=> grounded_ps_env_sem(P,Q,Env))).
fof(graph_env_grounded_ss, axiom,
  ! [P,A,Env] : (graph_env_mem(P,op_grounded_ss(A),Env) <=> grounded_ss_env_sem(P,A,Env))).
fof(graph_env_range, axiom,
  ! [P,A,Start,End,Env] : (graph_env_mem(P,op_range(A,Start,End),Env) <=> (graph_env_mem(P,A,Env) & range_select_env(P,A,Env,Start,End)))).

% Per-constructor backend/source agreement axioms. They make the generated
% whole-program theorem a contract-composition consistency check; they are
% not independently derived implementation-equivalence lemmas.
fof(optimized_source_empty_source_equiv, axiom,
  ! [P] : (source_mem(P,op_empty) <=> optimized_source_mem(P,op_empty))).
fof(optimized_source_input_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_input(X)) <=> optimized_source_mem(P,op_input(X)))).
fof(optimized_source_literal_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_literal(X)) <=> optimized_source_mem(P,op_literal(X)))).
fof(optimized_source_singleton_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_singleton(Q)) <=> optimized_source_mem(P,op_singleton(Q)))).
fof(optimized_source_union_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_union(A,B)) <=> optimized_source_mem(P,op_union(A,B)))).
fof(optimized_source_intersection_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_intersection(A,B)) <=> optimized_source_mem(P,op_intersection(A,B)))).
fof(optimized_source_diff_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_diff(A,B)) <=> optimized_source_mem(P,op_diff(A,B)))).
fof(optimized_source_restriction_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_restriction(A,B)) <=> optimized_source_mem(P,op_restriction(A,B)))).
fof(optimized_source_raffination_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_raffination(A,B)) <=> optimized_source_mem(P,op_raffination(A,B)))).
fof(optimized_source_product_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_product(A,B)) <=> optimized_source_mem(P,op_product(A,B)))).
fof(optimized_source_wrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_wrap(A,Q)) <=> optimized_source_mem(P,op_wrap(A,Q)))).
fof(optimized_source_unwrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_unwrap(A,Q)) <=> optimized_source_mem(P,op_unwrap(A,Q)))).
fof(optimized_source_tails_union_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_union(A)) <=> optimized_source_mem(P,op_tails_union(A)))).
fof(optimized_source_tails_intersection_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_intersection(A)) <=> optimized_source_mem(P,op_tails_intersection(A)))).
fof(optimized_source_prefix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_prefix_closure(A)) <=> optimized_source_mem(P,op_prefix_closure(A)))).
fof(optimized_source_suffix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_suffix_closure(A)) <=> optimized_source_mem(P,op_suffix_closure(A)))).
fof(optimized_source_tails_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_closure(A)) <=> optimized_source_mem(P,op_tails_closure(A)))).
fof(optimized_source_iter_source_equiv, axiom,
  ! [P,A,Sym,Rest,Body] : (source_mem(P,op_iter(A,Sym,Rest,Body)) <=> optimized_source_mem(P,op_iter(A,Sym,Rest,Body)))).
fof(optimized_source_fold_source_equiv, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (source_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> optimized_source_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)))).
fof(optimized_source_fixpoint_source_equiv, axiom,
  ! [P,A,Var,Step] : (source_mem(P,op_fixpoint(A,Var,Step)) <=> optimized_source_mem(P,op_fixpoint(A,Var,Step)))).
fof(optimized_source_grounded_ps_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_grounded_ps(Q)) <=> optimized_source_mem(P,op_grounded_ps(Q)))).
fof(optimized_source_grounded_ss_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_grounded_ss(A)) <=> optimized_source_mem(P,op_grounded_ss(A)))).
fof(optimized_source_range_source_equiv, axiom,
  ! [P,A,Start,End] : (source_mem(P,op_range(A,Start,End)) <=> optimized_source_mem(P,op_range(A,Start,End)))).
fof(optimized_source_call_source_equiv, axiom,
  ! [P,R,Refs,Args] : (source_mem(P,op_call(R,Refs,Args)) <=> optimized_source_mem(P,op_call(R,Refs,Args)))).
fof(trie_empty_source_equiv, axiom,
  ! [P] : (source_mem(P,op_empty) <=> trie_mem(P,op_empty))).
fof(trie_input_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_input(X)) <=> trie_mem(P,op_input(X)))).
fof(trie_literal_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_literal(X)) <=> trie_mem(P,op_literal(X)))).
fof(trie_singleton_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_singleton(Q)) <=> trie_mem(P,op_singleton(Q)))).
fof(trie_union_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_union(A,B)) <=> trie_mem(P,op_union(A,B)))).
fof(trie_intersection_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_intersection(A,B)) <=> trie_mem(P,op_intersection(A,B)))).
fof(trie_diff_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_diff(A,B)) <=> trie_mem(P,op_diff(A,B)))).
fof(trie_restriction_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_restriction(A,B)) <=> trie_mem(P,op_restriction(A,B)))).
fof(trie_raffination_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_raffination(A,B)) <=> trie_mem(P,op_raffination(A,B)))).
fof(trie_product_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_product(A,B)) <=> trie_mem(P,op_product(A,B)))).
fof(trie_wrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_wrap(A,Q)) <=> trie_mem(P,op_wrap(A,Q)))).
fof(trie_unwrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_unwrap(A,Q)) <=> trie_mem(P,op_unwrap(A,Q)))).
fof(trie_tails_union_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_union(A)) <=> trie_mem(P,op_tails_union(A)))).
fof(trie_tails_intersection_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_intersection(A)) <=> trie_mem(P,op_tails_intersection(A)))).
fof(trie_prefix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_prefix_closure(A)) <=> trie_mem(P,op_prefix_closure(A)))).
fof(trie_suffix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_suffix_closure(A)) <=> trie_mem(P,op_suffix_closure(A)))).
fof(trie_tails_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_closure(A)) <=> trie_mem(P,op_tails_closure(A)))).
fof(trie_iter_source_equiv, axiom,
  ! [P,A,Sym,Rest,Body] : (source_mem(P,op_iter(A,Sym,Rest,Body)) <=> trie_mem(P,op_iter(A,Sym,Rest,Body)))).
fof(trie_fold_source_equiv, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (source_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> trie_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)))).
fof(trie_fixpoint_source_equiv, axiom,
  ! [P,A,Var,Step] : (source_mem(P,op_fixpoint(A,Var,Step)) <=> trie_mem(P,op_fixpoint(A,Var,Step)))).
fof(trie_grounded_ps_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_grounded_ps(Q)) <=> trie_mem(P,op_grounded_ps(Q)))).
fof(trie_grounded_ss_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_grounded_ss(A)) <=> trie_mem(P,op_grounded_ss(A)))).
fof(trie_range_source_equiv, axiom,
  ! [P,A,Start,End] : (source_mem(P,op_range(A,Start,End)) <=> trie_mem(P,op_range(A,Start,End)))).
fof(trie_call_source_equiv, axiom,
  ! [P,R,Refs,Args] : (source_mem(P,op_call(R,Refs,Args)) <=> trie_mem(P,op_call(R,Refs,Args)))).
fof(zipper_empty_source_equiv, axiom,
  ! [P] : (source_mem(P,op_empty) <=> zipper_mem(P,op_empty))).
fof(zipper_input_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_input(X)) <=> zipper_mem(P,op_input(X)))).
fof(zipper_literal_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_literal(X)) <=> zipper_mem(P,op_literal(X)))).
fof(zipper_singleton_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_singleton(Q)) <=> zipper_mem(P,op_singleton(Q)))).
fof(zipper_union_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_union(A,B)) <=> zipper_mem(P,op_union(A,B)))).
fof(zipper_intersection_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_intersection(A,B)) <=> zipper_mem(P,op_intersection(A,B)))).
fof(zipper_diff_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_diff(A,B)) <=> zipper_mem(P,op_diff(A,B)))).
fof(zipper_restriction_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_restriction(A,B)) <=> zipper_mem(P,op_restriction(A,B)))).
fof(zipper_raffination_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_raffination(A,B)) <=> zipper_mem(P,op_raffination(A,B)))).
fof(zipper_product_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_product(A,B)) <=> zipper_mem(P,op_product(A,B)))).
fof(zipper_wrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_wrap(A,Q)) <=> zipper_mem(P,op_wrap(A,Q)))).
fof(zipper_unwrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_unwrap(A,Q)) <=> zipper_mem(P,op_unwrap(A,Q)))).
fof(zipper_tails_union_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_union(A)) <=> zipper_mem(P,op_tails_union(A)))).
fof(zipper_tails_intersection_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_intersection(A)) <=> zipper_mem(P,op_tails_intersection(A)))).
fof(zipper_prefix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_prefix_closure(A)) <=> zipper_mem(P,op_prefix_closure(A)))).
fof(zipper_suffix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_suffix_closure(A)) <=> zipper_mem(P,op_suffix_closure(A)))).
fof(zipper_tails_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_closure(A)) <=> zipper_mem(P,op_tails_closure(A)))).
fof(zipper_iter_source_equiv, axiom,
  ! [P,A,Sym,Rest,Body] : (source_mem(P,op_iter(A,Sym,Rest,Body)) <=> zipper_mem(P,op_iter(A,Sym,Rest,Body)))).
fof(zipper_fold_source_equiv, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (source_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> zipper_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)))).
fof(zipper_fixpoint_source_equiv, axiom,
  ! [P,A,Var,Step] : (source_mem(P,op_fixpoint(A,Var,Step)) <=> zipper_mem(P,op_fixpoint(A,Var,Step)))).
fof(zipper_grounded_ps_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_grounded_ps(Q)) <=> zipper_mem(P,op_grounded_ps(Q)))).
fof(zipper_grounded_ss_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_grounded_ss(A)) <=> zipper_mem(P,op_grounded_ss(A)))).
fof(zipper_range_source_equiv, axiom,
  ! [P,A,Start,End] : (source_mem(P,op_range(A,Start,End)) <=> zipper_mem(P,op_range(A,Start,End)))).
fof(zipper_call_source_equiv, axiom,
  ! [P,R,Refs,Args] : (source_mem(P,op_call(R,Refs,Args)) <=> zipper_mem(P,op_call(R,Refs,Args)))).
fof(graph_empty_source_equiv, axiom,
  ! [P] : (source_mem(P,op_empty) <=> graph_mem(P,op_empty))).
fof(graph_input_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_input(X)) <=> graph_mem(P,op_input(X)))).
fof(graph_literal_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_literal(X)) <=> graph_mem(P,op_literal(X)))).
fof(graph_singleton_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_singleton(Q)) <=> graph_mem(P,op_singleton(Q)))).
fof(graph_union_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_union(A,B)) <=> graph_mem(P,op_union(A,B)))).
fof(graph_intersection_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_intersection(A,B)) <=> graph_mem(P,op_intersection(A,B)))).
fof(graph_diff_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_diff(A,B)) <=> graph_mem(P,op_diff(A,B)))).
fof(graph_restriction_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_restriction(A,B)) <=> graph_mem(P,op_restriction(A,B)))).
fof(graph_raffination_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_raffination(A,B)) <=> graph_mem(P,op_raffination(A,B)))).
fof(graph_product_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_product(A,B)) <=> graph_mem(P,op_product(A,B)))).
fof(graph_wrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_wrap(A,Q)) <=> graph_mem(P,op_wrap(A,Q)))).
fof(graph_unwrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_unwrap(A,Q)) <=> graph_mem(P,op_unwrap(A,Q)))).
fof(graph_tails_union_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_union(A)) <=> graph_mem(P,op_tails_union(A)))).
fof(graph_tails_intersection_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_intersection(A)) <=> graph_mem(P,op_tails_intersection(A)))).
fof(graph_prefix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_prefix_closure(A)) <=> graph_mem(P,op_prefix_closure(A)))).
fof(graph_suffix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_suffix_closure(A)) <=> graph_mem(P,op_suffix_closure(A)))).
fof(graph_tails_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_closure(A)) <=> graph_mem(P,op_tails_closure(A)))).
fof(graph_iter_source_equiv, axiom,
  ! [P,A,Sym,Rest,Body] : (source_mem(P,op_iter(A,Sym,Rest,Body)) <=> graph_mem(P,op_iter(A,Sym,Rest,Body)))).
fof(graph_fold_source_equiv, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (source_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> graph_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)))).
fof(graph_fixpoint_source_equiv, axiom,
  ! [P,A,Var,Step] : (source_mem(P,op_fixpoint(A,Var,Step)) <=> graph_mem(P,op_fixpoint(A,Var,Step)))).
fof(graph_grounded_ps_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_grounded_ps(Q)) <=> graph_mem(P,op_grounded_ps(Q)))).
fof(graph_grounded_ss_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_grounded_ss(A)) <=> graph_mem(P,op_grounded_ss(A)))).
fof(graph_range_source_equiv, axiom,
  ! [P,A,Start,End] : (source_mem(P,op_range(A,Start,End)) <=> graph_mem(P,op_range(A,Start,End)))).
fof(graph_call_source_equiv, axiom,
  ! [P,R,Refs,Args] : (source_mem(P,op_call(R,Refs,Args)) <=> graph_mem(P,op_call(R,Refs,Args)))).


fof(path_constant_0, axiom, ! [P] : (path_matches(P,path_lit(a34)) <=> P = cons(a34,nil))).
fof(path_constant_1, axiom, ! [P] : (path_matches(P,path_lit(a31)) <=> P = cons(a31,nil))).
fof(path_constant_2, axiom, ! [P] : (path_matches(P,path_lit(a)) <=> P = nil)).
fof(path_constant_3, axiom, ! [P] : (path_matches(P,path_lit(a32)) <=> P = cons(a32,nil))).
fof(path_constant_4, axiom, ! [P] : (path_matches(P,path_lit(a33)) <=> P = cons(a33,nil))).
fof(literal_constant_0, axiom, ! [P] : (literal_mem(P,a312e317c322e317c322e327c332e317c332e327c332e337c342e317c342e327c342e337c342e34) <=> (P = cons(a31,cons(a31,nil)) | P = cons(a32,cons(a31,nil)) | P = cons(a32,cons(a32,nil)) | P = cons(a33,cons(a31,nil)) | P = cons(a33,cons(a32,nil)) | P = cons(a33,cons(a33,nil)) | P = cons(a34,cons(a31,nil)) | P = cons(a34,cons(a32,nil)) | P = cons(a34,cons(a33,nil)) | P = cons(a34,cons(a34,nil))))).
fof(literal_constant_1, axiom, ! [P] : (literal_mem(P,a312e312e327c312e322e337c312e332e347c312e342e357c322e312e337c322e322e347c322e332e357c322e342e367c332e312e347c332e322e357c332e332e367c332e342e377c342e312e357c342e322e367c342e332e377c342e342e38) <=> (P = cons(a31,cons(a31,cons(a32,nil))) | P = cons(a31,cons(a32,cons(a33,nil))) | P = cons(a31,cons(a33,cons(a34,nil))) | P = cons(a31,cons(a34,cons(a35,nil))) | P = cons(a32,cons(a31,cons(a33,nil))) | P = cons(a32,cons(a32,cons(a34,nil))) | P = cons(a32,cons(a33,cons(a35,nil))) | P = cons(a32,cons(a34,cons(a36,nil))) | P = cons(a33,cons(a31,cons(a34,nil))) | P = cons(a33,cons(a32,cons(a35,nil))) | P = cons(a33,cons(a33,cons(a36,nil))) | P = cons(a33,cons(a34,cons(a37,nil))) | P = cons(a34,cons(a31,cons(a35,nil))) | P = cons(a34,cons(a32,cons(a36,nil))) | P = cons(a34,cons(a33,cons(a37,nil))) | P = cons(a34,cons(a34,cons(a38,nil)))))).
fof(literal_constant_2, axiom, ! [P] : (literal_mem(P,a312e312e307c322e312e317c322e322e307c332e312e327c332e322e317c332e332e307c342e312e337c342e322e327c342e332e317c342e342e30) <=> (P = cons(a31,cons(a31,cons(a30,nil))) | P = cons(a32,cons(a31,cons(a31,nil))) | P = cons(a32,cons(a32,cons(a30,nil))) | P = cons(a33,cons(a31,cons(a32,nil))) | P = cons(a33,cons(a32,cons(a31,nil))) | P = cons(a33,cons(a33,cons(a30,nil))) | P = cons(a34,cons(a31,cons(a33,nil))) | P = cons(a34,cons(a32,cons(a32,nil))) | P = cons(a34,cons(a33,cons(a31,nil))) | P = cons(a34,cons(a34,cons(a30,nil)))))).

fof(full_program_term_0, axiom, fp_7 = op_literal(a312e317c322e317c322e327c332e317c332e327c332e337c342e317c342e327c342e337c342e34)).
fof(full_program_term_1, axiom, fp_6 = op_unwrap(fp_7,path_lit(a34))).
fof(full_program_term_2, axiom, fp_9 = op_empty).
fof(full_program_term_3, axiom, fp_8 = op_unwrap(fp_9,path_lit(a31))).
fof(full_program_term_4, axiom, fp_5 = op_diff(fp_6,fp_8)).
fof(full_program_term_5, axiom, fp_21 = op_singleton(path_ref(a69))).
fof(full_program_term_6, axiom, fp_20 = op_wrap(fp_21,path_lit(a31))).
fof(full_program_term_7, axiom, fp_23 = op_singleton(path_ref(a71))).
fof(full_program_term_8, axiom, fp_22 = op_wrap(fp_23,path_ref(a69))).
fof(full_program_term_9, axiom, fp_19 = op_union(fp_20,fp_22)).
fof(full_program_term_10, axiom, fp_27 = op_literal(a312e312e327c312e322e337c312e332e347c312e342e357c322e312e337c322e322e347c322e332e357c322e342e367c332e312e347c332e322e357c332e332e367c332e342e377c342e312e357c342e322e367c342e332e377c342e342e38)).
fof(full_program_term_11, axiom, fp_26 = op_unwrap(fp_27,path_lit(a31))).
fof(full_program_term_12, axiom, fp_25 = op_unwrap(fp_26,path_ref(a69))).
fof(full_program_term_13, axiom, fp_29 = op_unwrap(fp_27,path_ref(a71))).
fof(full_program_term_14, axiom, fp_28 = op_unwrap(fp_29,path_ref(a69))).
fof(full_program_term_15, axiom, fp_24 = op_product(fp_25,fp_28)).
fof(full_program_term_16, axiom, fp_18 = op_union(fp_19,fp_24)).
fof(full_program_term_17, axiom, fp_33 = op_literal(a312e312e307c322e312e317c322e322e307c332e312e327c332e322e317c332e332e307c342e312e337c342e322e327c342e332e317c342e342e30)).
fof(full_program_term_18, axiom, fp_32 = op_unwrap(fp_33,path_ref(a71))).
fof(full_program_term_19, axiom, fp_31 = op_unwrap(fp_32,path_ref(a69))).
fof(full_program_term_20, axiom, fp_30 = op_product(fp_25,fp_31)).
fof(full_program_term_21, axiom, fp_17 = op_union(fp_18,fp_30)).
fof(full_program_term_22, axiom, fp_36 = op_unwrap(fp_33,path_lit(a31))).
fof(full_program_term_23, axiom, fp_35 = op_unwrap(fp_36,path_ref(a69))).
fof(full_program_term_24, axiom, fp_34 = op_product(fp_35,fp_28)).
fof(full_program_term_25, axiom, fp_16 = op_union(fp_17,fp_34)).
fof(full_program_term_26, axiom, fp_37 = op_product(fp_35,fp_31)).
fof(full_program_term_27, axiom, fp_15 = op_union(fp_16,fp_37)).
fof(full_program_term_28, axiom, fp_14 = op_iter(fp_6,a69,a5f,fp_15)).
fof(full_program_term_29, axiom, fp_38 = op_product(fp_6,fp_6)).
fof(full_program_term_30, axiom, fp_13 = op_intersection(fp_14,fp_38)).
fof(full_program_term_31, axiom, fp_12 = op_union(fp_13,fp_9)).
fof(full_program_term_32, axiom, fp_11 = op_wrap(fp_12,path_lit(a))).
fof(full_program_term_33, axiom, fp_10 = op_wrap(fp_11,path_ref(a71))).
fof(full_program_term_34, axiom, fp_4 = op_iter(fp_5,a71,a5f,fp_10)).
fof(full_program_term_35, axiom, fp_42 = op_input(a74616b656e)).
fof(full_program_term_36, axiom, fp_41 = op_unwrap(fp_42,path_lit(a32))).
fof(full_program_term_37, axiom, fp_40 = op_diff(fp_6,fp_41)).
fof(full_program_term_38, axiom, fp_53 = op_wrap(fp_21,path_lit(a32))).
fof(full_program_term_39, axiom, fp_52 = op_union(fp_53,fp_22)).
fof(full_program_term_40, axiom, fp_56 = op_unwrap(fp_27,path_lit(a32))).
fof(full_program_term_41, axiom, fp_55 = op_unwrap(fp_56,path_ref(a69))).
fof(full_program_term_42, axiom, fp_54 = op_product(fp_55,fp_28)).
fof(full_program_term_43, axiom, fp_51 = op_union(fp_52,fp_54)).
fof(full_program_term_44, axiom, fp_57 = op_product(fp_55,fp_31)).
fof(full_program_term_45, axiom, fp_50 = op_union(fp_51,fp_57)).
fof(full_program_term_46, axiom, fp_60 = op_unwrap(fp_33,path_lit(a32))).
fof(full_program_term_47, axiom, fp_59 = op_unwrap(fp_60,path_ref(a69))).
fof(full_program_term_48, axiom, fp_58 = op_product(fp_59,fp_28)).
fof(full_program_term_49, axiom, fp_49 = op_union(fp_50,fp_58)).
fof(full_program_term_50, axiom, fp_61 = op_product(fp_59,fp_31)).
fof(full_program_term_51, axiom, fp_48 = op_union(fp_49,fp_61)).
fof(full_program_term_52, axiom, fp_47 = op_iter(fp_6,a69,a5f,fp_48)).
fof(full_program_term_53, axiom, fp_46 = op_intersection(fp_47,fp_38)).
fof(full_program_term_54, axiom, fp_45 = op_union(fp_46,fp_42)).
fof(full_program_term_55, axiom, fp_44 = op_wrap(fp_45,path_ref(a3068656466396365336139636534663231303965373232353238))).
fof(full_program_term_56, axiom, fp_43 = op_wrap(fp_44,path_ref(a71))).
fof(full_program_term_57, axiom, fp_39 = op_iter(fp_40,a71,a5f,fp_43)).
fof(full_program_term_58, axiom, fp_3 = op_iter(fp_4,a3068656466396365336139636534663231303965373232353238,a74616b656e,fp_39)).
fof(full_program_term_59, axiom, fp_63 = op_input(a723068346266666661373837396335396665313662326462323039)).
fof(full_program_term_60, axiom, fp_66 = op_unwrap(fp_42,path_lit(a33))).
fof(full_program_term_61, axiom, fp_65 = op_diff(fp_6,fp_66)).
fof(full_program_term_62, axiom, fp_77 = op_wrap(fp_21,path_lit(a33))).
fof(full_program_term_63, axiom, fp_76 = op_union(fp_77,fp_22)).
fof(full_program_term_64, axiom, fp_80 = op_unwrap(fp_27,path_lit(a33))).
fof(full_program_term_65, axiom, fp_79 = op_unwrap(fp_80,path_ref(a69))).
fof(full_program_term_66, axiom, fp_78 = op_product(fp_79,fp_28)).
fof(full_program_term_67, axiom, fp_75 = op_union(fp_76,fp_78)).
fof(full_program_term_68, axiom, fp_81 = op_product(fp_79,fp_31)).
fof(full_program_term_69, axiom, fp_74 = op_union(fp_75,fp_81)).
fof(full_program_term_70, axiom, fp_84 = op_unwrap(fp_33,path_lit(a33))).
fof(full_program_term_71, axiom, fp_83 = op_unwrap(fp_84,path_ref(a69))).
fof(full_program_term_72, axiom, fp_82 = op_product(fp_83,fp_28)).
fof(full_program_term_73, axiom, fp_73 = op_union(fp_74,fp_82)).
fof(full_program_term_74, axiom, fp_85 = op_product(fp_83,fp_31)).
fof(full_program_term_75, axiom, fp_72 = op_union(fp_73,fp_85)).
fof(full_program_term_76, axiom, fp_71 = op_iter(fp_6,a69,a5f,fp_72)).
fof(full_program_term_77, axiom, fp_70 = op_intersection(fp_71,fp_38)).
fof(full_program_term_78, axiom, fp_69 = op_union(fp_70,fp_42)).
fof(full_program_term_79, axiom, fp_68 = op_wrap(fp_69,path_concat(path_ref(a3068346266666661373837396335396665313662326462323039),path_ref(a3168346266666661373837396335396665313662326462323039)))).
fof(full_program_term_80, axiom, fp_67 = op_wrap(fp_68,path_ref(a71))).
fof(full_program_term_81, axiom, fp_64 = op_iter(fp_65,a71,a5f,fp_67)).
fof(full_program_term_82, axiom, fp_62 = op_iter(fp_63,a3168346266666661373837396335396665313662326462323039,a74616b656e,fp_64)).
fof(full_program_term_83, axiom, fp_2 = op_iter(fp_3,a3068346266666661373837396335396665313662326462323039,a723068346266666661373837396335396665313662326462323039,fp_62)).
fof(full_program_term_84, axiom, fp_87 = op_input(a723068396564343365643265663830323838386336313534623831)).
fof(full_program_term_85, axiom, fp_89 = op_input(a723168396564343365643265663830323838386336313534623831)).
fof(full_program_term_86, axiom, fp_92 = op_unwrap(fp_42,path_lit(a34))).
fof(full_program_term_87, axiom, fp_91 = op_diff(fp_6,fp_92)).
fof(full_program_term_88, axiom, fp_103 = op_wrap(fp_21,path_lit(a34))).
fof(full_program_term_89, axiom, fp_102 = op_union(fp_103,fp_22)).
fof(full_program_term_90, axiom, fp_106 = op_unwrap(fp_27,path_lit(a34))).
fof(full_program_term_91, axiom, fp_105 = op_unwrap(fp_106,path_ref(a69))).
fof(full_program_term_92, axiom, fp_104 = op_product(fp_105,fp_28)).
fof(full_program_term_93, axiom, fp_101 = op_union(fp_102,fp_104)).
fof(full_program_term_94, axiom, fp_107 = op_product(fp_105,fp_31)).
fof(full_program_term_95, axiom, fp_100 = op_union(fp_101,fp_107)).
fof(full_program_term_96, axiom, fp_110 = op_unwrap(fp_33,path_lit(a34))).
fof(full_program_term_97, axiom, fp_109 = op_unwrap(fp_110,path_ref(a69))).
fof(full_program_term_98, axiom, fp_108 = op_product(fp_109,fp_28)).
fof(full_program_term_99, axiom, fp_99 = op_union(fp_100,fp_108)).
fof(full_program_term_100, axiom, fp_111 = op_product(fp_109,fp_31)).
fof(full_program_term_101, axiom, fp_98 = op_union(fp_99,fp_111)).
fof(full_program_term_102, axiom, fp_97 = op_iter(fp_6,a69,a5f,fp_98)).
fof(full_program_term_103, axiom, fp_96 = op_intersection(fp_97,fp_38)).
fof(full_program_term_104, axiom, fp_95 = op_union(fp_96,fp_42)).
fof(full_program_term_105, axiom, fp_94 = op_wrap(fp_95,path_concat(path_concat(path_ref(a3068396564343365643265663830323838386336313534623831),path_ref(a3168396564343365643265663830323838386336313534623831)),path_ref(a3268396564343365643265663830323838386336313534623831)))).
fof(full_program_term_106, axiom, fp_93 = op_wrap(fp_94,path_ref(a71))).
fof(full_program_term_107, axiom, fp_90 = op_iter(fp_91,a71,a5f,fp_93)).
fof(full_program_term_108, axiom, fp_88 = op_iter(fp_89,a3268396564343365643265663830323838386336313534623831,a74616b656e,fp_90)).
fof(full_program_term_109, axiom, fp_86 = op_iter(fp_87,a3168396564343365643265663830323838386336313534623831,a723168396564343365643265663830323838386336313534623831,fp_88)).
fof(full_program_term_110, axiom, fp_1 = op_iter(fp_2,a3068396564343365643265663830323838386336313534623831,a723068396564343365643265663830323838386336313534623831,fp_86)).
fof(full_program_term_111, axiom, fp_113 = op_input(a723068346163633762333033303365396533303062336266333266)).
fof(full_program_term_112, axiom, fp_115 = op_input(a723168346163633762333033303365396533303062336266333266)).
fof(full_program_term_113, axiom, fp_117 = op_input(a723268346163633762333033303365396533303062336266333266)).
fof(full_program_term_114, axiom, fp_118 = op_singleton(path_concat(path_concat(path_concat(path_ref(a3068346163633762333033303365396533303062336266333266),path_ref(a3168346163633762333033303365396533303062336266333266)),path_ref(a3268346163633762333033303365396533303062336266333266)),path_ref(a3368346163633762333033303365396533303062336266333266)))).
fof(full_program_term_115, axiom, fp_116 = op_iter(fp_117,a3368346163633762333033303365396533303062336266333266,a5f,fp_118)).
fof(full_program_term_116, axiom, fp_114 = op_iter(fp_115,a3268346163633762333033303365396533303062336266333266,a723268346163633762333033303365396533303062336266333266,fp_116)).
fof(full_program_term_117, axiom, fp_112 = op_iter(fp_113,a3168346163633762333033303365396533303062336266333266,a723168346163633762333033303365396533303062336266333266,fp_114)).
fof(full_program_term_118, axiom, fp_0 = op_iter(fp_1,a3068346163633762333033303365396533303062336266333266,a723068346163633762333033303365396533303062336266333266,fp_112)).

fof(program_root, axiom, program_root = fp_0).

fof(conj, conjecture,
  ! [P] : (
    (source_mem(P,program_root) <=> optimized_source_mem(P,program_root)) &
    (source_mem(P,program_root) <=> trie_mem(P,program_root)) &
    (source_mem(P,program_root) <=> zipper_mem(P,program_root)) &
    (source_mem(P,program_root) <=> graph_mem(P,program_root))
  )
).
