% Generated by morkl.generateOpenProgramProofArtifacts
% scc-full-program: structural arbitrary-data full-program backend equivalence
% Direct SCC mutual-reachability program over arbitrary edge data.
%
% This is the structural ATP tier: the generated full MORKL program is
% emitted as a DAG of first-order terms. Backend equivalence is discharged
% through constructor-specific implementation lemmas over arbitrary
% interpretations of input spaces and path references. Iter is modeled with
% an explicit binding environment; Range is modeled as source membership plus
% ordered-rank selection. The remaining hard operators are named explicitly
% as shared semantic predicates rather than hidden behind bounded enumeration.
% General Fixpoint is exposed as the union-saturating base-or-step equation
% over the structural environment; leastness/positivity remains a proof
% obligation for future lowering-specific lemmas rather than a runtime cap.

% Abstract path and input interpretation.
fof(path_ref_sem, axiom, ! [P,R] : (path_matches(P,path_ref(R)) <=> path_ref_mem(P,R))).
fof(path_concat_sem, axiom,
  ! [P,A,B] : (path_matches(P,path_concat(A,B)) <=>
    ? [Q,R] : (path_matches(Q,A) & path_matches(R,B) & p_append(Q,R,P)))).
fof(path_grounded_pp_sem, axiom, ! [P,Q] : (path_matches(P,path_grounded_pp(Q)) <=> grounded_path_path_sem(P,Q))).
fof(path_grounded_sp_sem, axiom, ! [P,S] : (path_matches(P,path_grounded_sp(S)) <=> grounded_space_path_sem(P,S))).

fof(path_item_sem, axiom, ! [P,I] : (path_matches(P,path_item(I)) <=> P = cons(I,nil))).
fof(path_env_lit_sem, axiom, ! [P,X,Env] : (path_env_matches(P,path_lit(X),Env) <=> path_matches(P,path_lit(X)))).
fof(path_env_item_sem, axiom, ! [P,I,Env] : (path_env_matches(P,path_item(I),Env) <=> P = cons(I,nil))).
fof(path_env_concat_sem, axiom,
  ! [P,A,B,Env] : (path_env_matches(P,path_concat(A,B),Env) <=>
    ? [Q,R] : (path_env_matches(Q,A,Env) & path_env_matches(R,B,Env) & p_append(Q,R,P)))).
fof(path_env_grounded_pp_sem, axiom, ! [P,Q,Env] : (path_env_matches(P,path_grounded_pp(Q),Env) <=> grounded_path_path_env_sem(P,Q,Env))).
fof(path_env_grounded_sp_sem, axiom, ! [P,S,Env] : (path_env_matches(P,path_grounded_sp(S),Env) <=> grounded_space_path_env_sem(P,S,Env))).

fof(path_lookup_hit, axiom,
  ! [P,R,Q,Outer] : (path_lookup_matches(P,R,env_path(R,Q,Outer)) <=> path_env_matches(P,Q,Outer))).
fof(path_lookup_miss_path, axiom,
  ! [P,R,Other,Q,Outer] : (R != Other => (path_lookup_matches(P,R,env_path(Other,Q,Outer)) <=> path_lookup_matches(P,R,Outer)))).
fof(path_lookup_skip_space, axiom,
  ! [P,R,Name,S,Outer] : (path_lookup_matches(P,R,env_space(Name,S,Outer)) <=> path_lookup_matches(P,R,Outer))).
fof(path_lookup_empty, axiom, ! [P,R] : (path_lookup_matches(P,R,env_empty) <=> path_ref_mem(P,R))).
fof(path_env_ref_sem, axiom, ! [P,R,Env] : (path_env_matches(P,path_ref(R),Env) <=> path_lookup_matches(P,R,Env))).

% Range is order-sensitive.  The structural FOL layer exposes the exact
% shape of the implementation contract: membership in the source, a rank in
% that ordered source, normalized public bounds, and a half-open selected
% interval.  The rank/count/bounds relations are the remaining ordered-trie
% proof hooks; they are shared by all backends.
fof(range_select_rank, axiom,
  ! [P,A,Env,Start,End] : (range_select_env(P,A,Env,Start,End) <=>
    ? [K,N,Lo,Hi] : (
      range_rank_env(P,A,Env,K) &
      range_count_env(A,Env,N) &
      range_bounds(N,Start,End,Lo,Hi) &
      int_le(Lo,K) &
      int_lt(K,Hi)))).
fof(range_bounds_full_sentinel, axiom, ! [N] : range_bounds(N,n0,n0,n0,N)).
fof(range_bounds_empty_one_one, axiom, ! [N] : range_bounds(N,n1,n1,n0,n0)).
fof(range_bounds_functional, axiom,
  ! [N,Start,End,Lo1,Hi1,Lo2,Hi2] : (
    (range_bounds(N,Start,End,Lo1,Hi1) & range_bounds(N,Start,End,Lo2,Hi2)) =>
    (Lo1 = Lo2 & Hi1 = Hi2))).
fof(int_le_excludes_reverse_lt, axiom, ! [A,B] : (int_le(A,B) => ~int_lt(B,A))).

% Shared semantic frontiers for operators whose full FOL expansion still
% needs grounded host functions, folds, or least-fixed-point theory. They
% are per-operator, so generated certificates show exactly where stronger
% lemmas remain to be added.
fof(call_backend_shared, axiom, ! [P,R,Refs,Args] : (
  source_mem(P,op_call(R,Refs,Args)) <=>
  optimized_source_mem(P,op_call(R,Refs,Args)))).
fof(call_trie_shared, axiom, ! [P,R,Refs,Args] : (
  source_mem(P,op_call(R,Refs,Args)) <=> trie_mem(P,op_call(R,Refs,Args)))).
fof(call_zipper_shared, axiom, ! [P,R,Refs,Args] : (
  source_mem(P,op_call(R,Refs,Args)) <=> zipper_mem(P,op_call(R,Refs,Args)))).
fof(call_graph_shared, axiom, ! [P,R,Refs,Args] : (
  source_mem(P,op_call(R,Refs,Args)) <=> graph_mem(P,op_call(R,Refs,Args)))).

fof(source_empty, axiom,
  ! [P] : (~ source_mem(P,op_empty))).
fof(source_input, axiom,
  ! [P,X] : (source_mem(P,op_input(X)) <=> input_mem(P,X))).
fof(source_literal, axiom,
  ! [P,X] : (source_mem(P,op_literal(X)) <=> literal_mem(P,X))).
fof(source_singleton, axiom,
  ! [P,Q] : (source_mem(P,op_singleton(Q)) <=> path_matches(P,Q))).
fof(source_union, axiom,
  ! [P,A,B] : (source_mem(P,op_union(A,B)) <=> (source_mem(P,A) | source_mem(P,B)))).
fof(source_intersection, axiom,
  ! [P,A,B] : (source_mem(P,op_intersection(A,B)) <=> (source_mem(P,A) & source_mem(P,B)))).
fof(source_diff, axiom,
  ! [P,A,B] : (source_mem(P,op_diff(A,B)) <=> (source_mem(P,A) & ~ source_mem(P,B)))).
fof(source_restriction, axiom,
  ! [P,A,B] : (source_mem(P,op_restriction(A,B)) <=> (source_mem(P,A) & ? [Q] : (source_mem(Q,B) & p_prefix(Q,P))))).
fof(source_raffination, axiom,
  ! [P,A,B] : (source_mem(P,op_raffination(A,B)) <=> (source_mem(P,A) & ~ ? [Q] : (source_mem(Q,B) & p_prefix(Q,P))))).
fof(source_product, axiom,
  ! [P,A,B] : (source_mem(P,op_product(A,B)) <=> ? [Q,R] : (source_mem(Q,A) & source_mem(R,B) & p_append(Q,R,P)))).
fof(source_wrap, axiom,
  ! [P,A,Q] : (source_mem(P,op_wrap(A,Q)) <=> ? [Prefix,Tail] : (path_matches(Prefix,Q) & source_mem(Tail,A) & p_append(Prefix,Tail,P)))).
fof(source_unwrap, axiom,
  ! [P,A,Q] : (source_mem(P,op_unwrap(A,Q)) <=> ? [Prefix,Full] : (path_matches(Prefix,Q) & p_append(Prefix,P,Full) & source_mem(Full,A)))).
fof(source_tails_union, axiom,
  ! [P,A] : (source_mem(P,op_tails_union(A)) <=> ? [I] : source_mem(cons(I,P),A))).
fof(source_tails_intersection, axiom,
  ! [P,A] : (source_mem(P,op_tails_intersection(A)) <=> ((? [I,Q] : source_mem(cons(I,Q),A)) & ! [I] : ((? [Q] : source_mem(cons(I,Q),A)) => source_mem(cons(I,P),A))))).
fof(source_prefix_closure, axiom,
  ! [P,A] : (source_mem(P,op_prefix_closure(A)) <=> (P != nil & ? [Q] : (source_mem(Q,A) & p_prefix(P,Q))))).
fof(source_suffix_closure, axiom,
  ! [P,A] : (source_mem(P,op_suffix_closure(A)) <=> (P != nil & ? [Q] : (source_mem(Q,A) & p_suffix(P,Q))))).
fof(source_tails_closure, axiom,
  ! [P,A] : (source_mem(P,op_tails_closure(A)) <=> (((P = nil) & ? [Q] : source_mem(Q,A)) | (P != nil & ? [Q] : (source_mem(Q,A) & p_suffix(P,Q)))))).
fof(source_iter, axiom,
  ! [P,A,Sym,Rest,Body] : (source_mem(P,op_iter(A,Sym,Rest,Body)) <=> source_env_mem(P,op_iter(A,Sym,Rest,Body),env_empty))).
fof(source_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (source_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> fold_sem(P,A,Initial,Acc,Sym,Rest,Body,Update))).
fof(source_fixpoint, axiom,
  ! [P,A,Var,Step] : (source_mem(P,op_fixpoint(A,Var,Step)) <=> source_env_mem(P,op_fixpoint(A,Var,Step),env_empty))).
fof(source_grounded_ps, axiom,
  ! [P,Q] : (source_mem(P,op_grounded_ps(Q)) <=> grounded_ps_sem(P,Q))).
fof(source_grounded_ss, axiom,
  ! [P,A] : (source_mem(P,op_grounded_ss(A)) <=> grounded_ss_sem(P,A))).
fof(source_range, axiom,
  ! [P,A,Start,End] : (source_mem(P,op_range(A,Start,End)) <=> source_env_mem(P,op_range(A,Start,End),env_empty))).
fof(source_space_lookup_hit, axiom,
  ! [P,X,S,Outer] : (source_space_lookup_mem(P,X,env_space(X,S,Outer)) <=> source_env_mem(P,S,Outer))).
fof(source_space_lookup_miss_space, axiom,
  ! [P,X,Other,S,Outer] : (X != Other => (source_space_lookup_mem(P,X,env_space(Other,S,Outer)) <=> source_space_lookup_mem(P,X,Outer)))).
fof(source_space_lookup_skip_path, axiom,
  ! [P,X,R,Q,Outer] : (source_space_lookup_mem(P,X,env_path(R,Q,Outer)) <=> source_space_lookup_mem(P,X,Outer))).
fof(source_space_lookup_empty, axiom,
  ! [P,X] : (source_space_lookup_mem(P,X,env_empty) <=> input_mem(P,X))).
fof(source_env_empty, axiom,
  ! [P,Env] : (~ source_env_mem(P,op_empty,Env))).
fof(source_env_input, axiom,
  ! [P,X,Env] : (source_env_mem(P,op_input(X),Env) <=> source_space_lookup_mem(P,X,Env))).
fof(source_env_literal, axiom,
  ! [P,X,Env] : (source_env_mem(P,op_literal(X),Env) <=> literal_mem(P,X))).
fof(source_env_singleton, axiom,
  ! [P,Q,Env] : (source_env_mem(P,op_singleton(Q),Env) <=> path_env_matches(P,Q,Env))).
fof(source_env_union, axiom,
  ! [P,A,B,Env] : (source_env_mem(P,op_union(A,B),Env) <=> (source_env_mem(P,A,Env) | source_env_mem(P,B,Env)))).
fof(source_env_intersection, axiom,
  ! [P,A,B,Env] : (source_env_mem(P,op_intersection(A,B),Env) <=> (source_env_mem(P,A,Env) & source_env_mem(P,B,Env)))).
fof(source_env_diff, axiom,
  ! [P,A,B,Env] : (source_env_mem(P,op_diff(A,B),Env) <=> (source_env_mem(P,A,Env) & ~ source_env_mem(P,B,Env)))).
fof(source_env_restriction, axiom,
  ! [P,A,B,Env] : (source_env_mem(P,op_restriction(A,B),Env) <=> (source_env_mem(P,A,Env) & ? [Q] : (source_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(source_env_raffination, axiom,
  ! [P,A,B,Env] : (source_env_mem(P,op_raffination(A,B),Env) <=> (source_env_mem(P,A,Env) & ~ ? [Q] : (source_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(source_env_product, axiom,
  ! [P,A,B,Env] : (source_env_mem(P,op_product(A,B),Env) <=> ? [Q,R] : (source_env_mem(Q,A,Env) & source_env_mem(R,B,Env) & p_append(Q,R,P)))).
fof(source_env_wrap, axiom,
  ! [P,A,Q,Env] : (source_env_mem(P,op_wrap(A,Q),Env) <=> ? [Prefix,Tail] : (path_env_matches(Prefix,Q,Env) & source_env_mem(Tail,A,Env) & p_append(Prefix,Tail,P)))).
fof(source_env_unwrap, axiom,
  ! [P,A,Q,Env] : (source_env_mem(P,op_unwrap(A,Q),Env) <=> ? [Prefix,Full] : (path_env_matches(Prefix,Q,Env) & p_append(Prefix,P,Full) & source_env_mem(Full,A,Env)))).
fof(source_env_tails_union, axiom,
  ! [P,A,Env] : (source_env_mem(P,op_tails_union(A),Env) <=> ? [I] : source_env_mem(cons(I,P),A,Env))).
fof(source_env_tails_intersection, axiom,
  ! [P,A,Env] : (source_env_mem(P,op_tails_intersection(A),Env) <=> ((? [I,Q] : source_env_mem(cons(I,Q),A,Env)) & ! [I] : ((? [Q] : source_env_mem(cons(I,Q),A,Env)) => source_env_mem(cons(I,P),A,Env))))).
fof(source_env_prefix_closure, axiom,
  ! [P,A,Env] : (source_env_mem(P,op_prefix_closure(A),Env) <=> (P != nil & ? [Q] : (source_env_mem(Q,A,Env) & p_prefix(P,Q))))).
fof(source_env_suffix_closure, axiom,
  ! [P,A,Env] : (source_env_mem(P,op_suffix_closure(A),Env) <=> (P != nil & ? [Q] : (source_env_mem(Q,A,Env) & p_suffix(P,Q))))).
fof(source_env_tails_closure, axiom,
  ! [P,A,Env] : (source_env_mem(P,op_tails_closure(A),Env) <=> (((P = nil) & ? [Q] : source_env_mem(Q,A,Env)) | (P != nil & ? [Q] : (source_env_mem(Q,A,Env) & p_suffix(P,Q)))))).
fof(source_env_iter, axiom,
  ! [P,A,Sym,Rest,Body,Env] : (source_env_mem(P,op_iter(A,Sym,Rest,Body),Env) <=> ? [I] : ((? [Q] : source_env_mem(cons(I,Q),A,Env)) & source_env_mem(P,Body,env_space(Rest,op_child_env(A,I,Env),env_path(Sym,path_item(I),Env)))))).
fof(source_env_child, axiom,
  ! [P,A,I,Captured,Env] : (source_env_mem(P,op_child_env(A,I,Captured),Env) <=> source_env_mem(cons(I,P),A,Captured))).
fof(source_env_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update,Env] : (source_env_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update),Env) <=> fold_env_sem(P,A,Initial,Acc,Sym,Rest,Body,Update,Env))).
fof(source_env_fixpoint, axiom,
  ! [P,A,Var,Step,Env] : (source_env_mem(P,op_fixpoint(A,Var,Step),Env) <=> (source_env_mem(P,A,Env) | source_env_mem(P,Step,env_space(Var,op_fixpoint(A,Var,Step),Env))))).
fof(source_env_grounded_ps, axiom,
  ! [P,Q,Env] : (source_env_mem(P,op_grounded_ps(Q),Env) <=> grounded_ps_env_sem(P,Q,Env))).
fof(source_env_grounded_ss, axiom,
  ! [P,A,Env] : (source_env_mem(P,op_grounded_ss(A),Env) <=> grounded_ss_env_sem(P,A,Env))).
fof(source_env_range, axiom,
  ! [P,A,Start,End,Env] : (source_env_mem(P,op_range(A,Start,End),Env) <=> (source_env_mem(P,A,Env) & range_select_env(P,A,Env,Start,End)))).
fof(optimized_source_empty, axiom,
  ! [P] : (~ optimized_source_mem(P,op_empty))).
fof(optimized_source_input, axiom,
  ! [P,X] : (optimized_source_mem(P,op_input(X)) <=> input_mem(P,X))).
fof(optimized_source_literal, axiom,
  ! [P,X] : (optimized_source_mem(P,op_literal(X)) <=> literal_mem(P,X))).
fof(optimized_source_singleton, axiom,
  ! [P,Q] : (optimized_source_mem(P,op_singleton(Q)) <=> path_matches(P,Q))).
fof(optimized_source_union, axiom,
  ! [P,A,B] : (optimized_source_mem(P,op_union(A,B)) <=> (optimized_source_mem(P,A) | optimized_source_mem(P,B)))).
fof(optimized_source_intersection, axiom,
  ! [P,A,B] : (optimized_source_mem(P,op_intersection(A,B)) <=> (optimized_source_mem(P,A) & optimized_source_mem(P,B)))).
fof(optimized_source_diff, axiom,
  ! [P,A,B] : (optimized_source_mem(P,op_diff(A,B)) <=> (optimized_source_mem(P,A) & ~ optimized_source_mem(P,B)))).
fof(optimized_source_restriction, axiom,
  ! [P,A,B] : (optimized_source_mem(P,op_restriction(A,B)) <=> (optimized_source_mem(P,A) & ? [Q] : (optimized_source_mem(Q,B) & p_prefix(Q,P))))).
fof(optimized_source_raffination, axiom,
  ! [P,A,B] : (optimized_source_mem(P,op_raffination(A,B)) <=> (optimized_source_mem(P,A) & ~ ? [Q] : (optimized_source_mem(Q,B) & p_prefix(Q,P))))).
fof(optimized_source_product, axiom,
  ! [P,A,B] : (optimized_source_mem(P,op_product(A,B)) <=> ? [Q,R] : (optimized_source_mem(Q,A) & optimized_source_mem(R,B) & p_append(Q,R,P)))).
fof(optimized_source_wrap, axiom,
  ! [P,A,Q] : (optimized_source_mem(P,op_wrap(A,Q)) <=> ? [Prefix,Tail] : (path_matches(Prefix,Q) & optimized_source_mem(Tail,A) & p_append(Prefix,Tail,P)))).
fof(optimized_source_unwrap, axiom,
  ! [P,A,Q] : (optimized_source_mem(P,op_unwrap(A,Q)) <=> ? [Prefix,Full] : (path_matches(Prefix,Q) & p_append(Prefix,P,Full) & optimized_source_mem(Full,A)))).
fof(optimized_source_tails_union, axiom,
  ! [P,A] : (optimized_source_mem(P,op_tails_union(A)) <=> ? [I] : optimized_source_mem(cons(I,P),A))).
fof(optimized_source_tails_intersection, axiom,
  ! [P,A] : (optimized_source_mem(P,op_tails_intersection(A)) <=> ((? [I,Q] : optimized_source_mem(cons(I,Q),A)) & ! [I] : ((? [Q] : optimized_source_mem(cons(I,Q),A)) => optimized_source_mem(cons(I,P),A))))).
fof(optimized_source_prefix_closure, axiom,
  ! [P,A] : (optimized_source_mem(P,op_prefix_closure(A)) <=> (P != nil & ? [Q] : (optimized_source_mem(Q,A) & p_prefix(P,Q))))).
fof(optimized_source_suffix_closure, axiom,
  ! [P,A] : (optimized_source_mem(P,op_suffix_closure(A)) <=> (P != nil & ? [Q] : (optimized_source_mem(Q,A) & p_suffix(P,Q))))).
fof(optimized_source_tails_closure, axiom,
  ! [P,A] : (optimized_source_mem(P,op_tails_closure(A)) <=> (((P = nil) & ? [Q] : optimized_source_mem(Q,A)) | (P != nil & ? [Q] : (optimized_source_mem(Q,A) & p_suffix(P,Q)))))).
fof(optimized_source_iter, axiom,
  ! [P,A,Sym,Rest,Body] : (optimized_source_mem(P,op_iter(A,Sym,Rest,Body)) <=> optimized_source_env_mem(P,op_iter(A,Sym,Rest,Body),env_empty))).
fof(optimized_source_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (optimized_source_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> fold_sem(P,A,Initial,Acc,Sym,Rest,Body,Update))).
fof(optimized_source_fixpoint, axiom,
  ! [P,A,Var,Step] : (optimized_source_mem(P,op_fixpoint(A,Var,Step)) <=> optimized_source_env_mem(P,op_fixpoint(A,Var,Step),env_empty))).
fof(optimized_source_grounded_ps, axiom,
  ! [P,Q] : (optimized_source_mem(P,op_grounded_ps(Q)) <=> grounded_ps_sem(P,Q))).
fof(optimized_source_grounded_ss, axiom,
  ! [P,A] : (optimized_source_mem(P,op_grounded_ss(A)) <=> grounded_ss_sem(P,A))).
fof(optimized_source_range, axiom,
  ! [P,A,Start,End] : (optimized_source_mem(P,op_range(A,Start,End)) <=> optimized_source_env_mem(P,op_range(A,Start,End),env_empty))).
fof(optimized_source_space_lookup_hit, axiom,
  ! [P,X,S,Outer] : (optimized_source_space_lookup_mem(P,X,env_space(X,S,Outer)) <=> optimized_source_env_mem(P,S,Outer))).
fof(optimized_source_space_lookup_miss_space, axiom,
  ! [P,X,Other,S,Outer] : (X != Other => (optimized_source_space_lookup_mem(P,X,env_space(Other,S,Outer)) <=> optimized_source_space_lookup_mem(P,X,Outer)))).
fof(optimized_source_space_lookup_skip_path, axiom,
  ! [P,X,R,Q,Outer] : (optimized_source_space_lookup_mem(P,X,env_path(R,Q,Outer)) <=> optimized_source_space_lookup_mem(P,X,Outer))).
fof(optimized_source_space_lookup_empty, axiom,
  ! [P,X] : (optimized_source_space_lookup_mem(P,X,env_empty) <=> input_mem(P,X))).
fof(optimized_source_env_empty, axiom,
  ! [P,Env] : (~ optimized_source_env_mem(P,op_empty,Env))).
fof(optimized_source_env_input, axiom,
  ! [P,X,Env] : (optimized_source_env_mem(P,op_input(X),Env) <=> optimized_source_space_lookup_mem(P,X,Env))).
fof(optimized_source_env_literal, axiom,
  ! [P,X,Env] : (optimized_source_env_mem(P,op_literal(X),Env) <=> literal_mem(P,X))).
fof(optimized_source_env_singleton, axiom,
  ! [P,Q,Env] : (optimized_source_env_mem(P,op_singleton(Q),Env) <=> path_env_matches(P,Q,Env))).
fof(optimized_source_env_union, axiom,
  ! [P,A,B,Env] : (optimized_source_env_mem(P,op_union(A,B),Env) <=> (optimized_source_env_mem(P,A,Env) | optimized_source_env_mem(P,B,Env)))).
fof(optimized_source_env_intersection, axiom,
  ! [P,A,B,Env] : (optimized_source_env_mem(P,op_intersection(A,B),Env) <=> (optimized_source_env_mem(P,A,Env) & optimized_source_env_mem(P,B,Env)))).
fof(optimized_source_env_diff, axiom,
  ! [P,A,B,Env] : (optimized_source_env_mem(P,op_diff(A,B),Env) <=> (optimized_source_env_mem(P,A,Env) & ~ optimized_source_env_mem(P,B,Env)))).
fof(optimized_source_env_restriction, axiom,
  ! [P,A,B,Env] : (optimized_source_env_mem(P,op_restriction(A,B),Env) <=> (optimized_source_env_mem(P,A,Env) & ? [Q] : (optimized_source_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(optimized_source_env_raffination, axiom,
  ! [P,A,B,Env] : (optimized_source_env_mem(P,op_raffination(A,B),Env) <=> (optimized_source_env_mem(P,A,Env) & ~ ? [Q] : (optimized_source_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(optimized_source_env_product, axiom,
  ! [P,A,B,Env] : (optimized_source_env_mem(P,op_product(A,B),Env) <=> ? [Q,R] : (optimized_source_env_mem(Q,A,Env) & optimized_source_env_mem(R,B,Env) & p_append(Q,R,P)))).
fof(optimized_source_env_wrap, axiom,
  ! [P,A,Q,Env] : (optimized_source_env_mem(P,op_wrap(A,Q),Env) <=> ? [Prefix,Tail] : (path_env_matches(Prefix,Q,Env) & optimized_source_env_mem(Tail,A,Env) & p_append(Prefix,Tail,P)))).
fof(optimized_source_env_unwrap, axiom,
  ! [P,A,Q,Env] : (optimized_source_env_mem(P,op_unwrap(A,Q),Env) <=> ? [Prefix,Full] : (path_env_matches(Prefix,Q,Env) & p_append(Prefix,P,Full) & optimized_source_env_mem(Full,A,Env)))).
fof(optimized_source_env_tails_union, axiom,
  ! [P,A,Env] : (optimized_source_env_mem(P,op_tails_union(A),Env) <=> ? [I] : optimized_source_env_mem(cons(I,P),A,Env))).
fof(optimized_source_env_tails_intersection, axiom,
  ! [P,A,Env] : (optimized_source_env_mem(P,op_tails_intersection(A),Env) <=> ((? [I,Q] : optimized_source_env_mem(cons(I,Q),A,Env)) & ! [I] : ((? [Q] : optimized_source_env_mem(cons(I,Q),A,Env)) => optimized_source_env_mem(cons(I,P),A,Env))))).
fof(optimized_source_env_prefix_closure, axiom,
  ! [P,A,Env] : (optimized_source_env_mem(P,op_prefix_closure(A),Env) <=> (P != nil & ? [Q] : (optimized_source_env_mem(Q,A,Env) & p_prefix(P,Q))))).
fof(optimized_source_env_suffix_closure, axiom,
  ! [P,A,Env] : (optimized_source_env_mem(P,op_suffix_closure(A),Env) <=> (P != nil & ? [Q] : (optimized_source_env_mem(Q,A,Env) & p_suffix(P,Q))))).
fof(optimized_source_env_tails_closure, axiom,
  ! [P,A,Env] : (optimized_source_env_mem(P,op_tails_closure(A),Env) <=> (((P = nil) & ? [Q] : optimized_source_env_mem(Q,A,Env)) | (P != nil & ? [Q] : (optimized_source_env_mem(Q,A,Env) & p_suffix(P,Q)))))).
fof(optimized_source_env_iter, axiom,
  ! [P,A,Sym,Rest,Body,Env] : (optimized_source_env_mem(P,op_iter(A,Sym,Rest,Body),Env) <=> ? [I] : ((? [Q] : optimized_source_env_mem(cons(I,Q),A,Env)) & optimized_source_env_mem(P,Body,env_space(Rest,op_child_env(A,I,Env),env_path(Sym,path_item(I),Env)))))).
fof(optimized_source_env_child, axiom,
  ! [P,A,I,Captured,Env] : (optimized_source_env_mem(P,op_child_env(A,I,Captured),Env) <=> optimized_source_env_mem(cons(I,P),A,Captured))).
fof(optimized_source_env_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update,Env] : (optimized_source_env_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update),Env) <=> fold_env_sem(P,A,Initial,Acc,Sym,Rest,Body,Update,Env))).
fof(optimized_source_env_fixpoint, axiom,
  ! [P,A,Var,Step,Env] : (optimized_source_env_mem(P,op_fixpoint(A,Var,Step),Env) <=> (optimized_source_env_mem(P,A,Env) | optimized_source_env_mem(P,Step,env_space(Var,op_fixpoint(A,Var,Step),Env))))).
fof(optimized_source_env_grounded_ps, axiom,
  ! [P,Q,Env] : (optimized_source_env_mem(P,op_grounded_ps(Q),Env) <=> grounded_ps_env_sem(P,Q,Env))).
fof(optimized_source_env_grounded_ss, axiom,
  ! [P,A,Env] : (optimized_source_env_mem(P,op_grounded_ss(A),Env) <=> grounded_ss_env_sem(P,A,Env))).
fof(optimized_source_env_range, axiom,
  ! [P,A,Start,End,Env] : (optimized_source_env_mem(P,op_range(A,Start,End),Env) <=> (optimized_source_env_mem(P,A,Env) & range_select_env(P,A,Env,Start,End)))).
fof(trie_empty, axiom,
  ! [P] : (~ trie_mem(P,op_empty))).
fof(trie_input, axiom,
  ! [P,X] : (trie_mem(P,op_input(X)) <=> input_mem(P,X))).
fof(trie_literal, axiom,
  ! [P,X] : (trie_mem(P,op_literal(X)) <=> literal_mem(P,X))).
fof(trie_singleton, axiom,
  ! [P,Q] : (trie_mem(P,op_singleton(Q)) <=> path_matches(P,Q))).
fof(trie_union, axiom,
  ! [P,A,B] : (trie_mem(P,op_union(A,B)) <=> (trie_mem(P,A) | trie_mem(P,B)))).
fof(trie_intersection, axiom,
  ! [P,A,B] : (trie_mem(P,op_intersection(A,B)) <=> (trie_mem(P,A) & trie_mem(P,B)))).
fof(trie_diff, axiom,
  ! [P,A,B] : (trie_mem(P,op_diff(A,B)) <=> (trie_mem(P,A) & ~ trie_mem(P,B)))).
fof(trie_restriction, axiom,
  ! [P,A,B] : (trie_mem(P,op_restriction(A,B)) <=> (trie_mem(P,A) & ? [Q] : (trie_mem(Q,B) & p_prefix(Q,P))))).
fof(trie_raffination, axiom,
  ! [P,A,B] : (trie_mem(P,op_raffination(A,B)) <=> (trie_mem(P,A) & ~ ? [Q] : (trie_mem(Q,B) & p_prefix(Q,P))))).
fof(trie_product, axiom,
  ! [P,A,B] : (trie_mem(P,op_product(A,B)) <=> ? [Q,R] : (trie_mem(Q,A) & trie_mem(R,B) & p_append(Q,R,P)))).
fof(trie_wrap, axiom,
  ! [P,A,Q] : (trie_mem(P,op_wrap(A,Q)) <=> ? [Prefix,Tail] : (path_matches(Prefix,Q) & trie_mem(Tail,A) & p_append(Prefix,Tail,P)))).
fof(trie_unwrap, axiom,
  ! [P,A,Q] : (trie_mem(P,op_unwrap(A,Q)) <=> ? [Prefix,Full] : (path_matches(Prefix,Q) & p_append(Prefix,P,Full) & trie_mem(Full,A)))).
fof(trie_tails_union, axiom,
  ! [P,A] : (trie_mem(P,op_tails_union(A)) <=> ? [I] : trie_mem(cons(I,P),A))).
fof(trie_tails_intersection, axiom,
  ! [P,A] : (trie_mem(P,op_tails_intersection(A)) <=> ((? [I,Q] : trie_mem(cons(I,Q),A)) & ! [I] : ((? [Q] : trie_mem(cons(I,Q),A)) => trie_mem(cons(I,P),A))))).
fof(trie_prefix_closure, axiom,
  ! [P,A] : (trie_mem(P,op_prefix_closure(A)) <=> (P != nil & ? [Q] : (trie_mem(Q,A) & p_prefix(P,Q))))).
fof(trie_suffix_closure, axiom,
  ! [P,A] : (trie_mem(P,op_suffix_closure(A)) <=> (P != nil & ? [Q] : (trie_mem(Q,A) & p_suffix(P,Q))))).
fof(trie_tails_closure, axiom,
  ! [P,A] : (trie_mem(P,op_tails_closure(A)) <=> (((P = nil) & ? [Q] : trie_mem(Q,A)) | (P != nil & ? [Q] : (trie_mem(Q,A) & p_suffix(P,Q)))))).
fof(trie_iter, axiom,
  ! [P,A,Sym,Rest,Body] : (trie_mem(P,op_iter(A,Sym,Rest,Body)) <=> trie_env_mem(P,op_iter(A,Sym,Rest,Body),env_empty))).
fof(trie_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (trie_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> fold_sem(P,A,Initial,Acc,Sym,Rest,Body,Update))).
fof(trie_fixpoint, axiom,
  ! [P,A,Var,Step] : (trie_mem(P,op_fixpoint(A,Var,Step)) <=> trie_env_mem(P,op_fixpoint(A,Var,Step),env_empty))).
fof(trie_grounded_ps, axiom,
  ! [P,Q] : (trie_mem(P,op_grounded_ps(Q)) <=> grounded_ps_sem(P,Q))).
fof(trie_grounded_ss, axiom,
  ! [P,A] : (trie_mem(P,op_grounded_ss(A)) <=> grounded_ss_sem(P,A))).
fof(trie_range, axiom,
  ! [P,A,Start,End] : (trie_mem(P,op_range(A,Start,End)) <=> trie_env_mem(P,op_range(A,Start,End),env_empty))).
fof(trie_space_lookup_hit, axiom,
  ! [P,X,S,Outer] : (trie_space_lookup_mem(P,X,env_space(X,S,Outer)) <=> trie_env_mem(P,S,Outer))).
fof(trie_space_lookup_miss_space, axiom,
  ! [P,X,Other,S,Outer] : (X != Other => (trie_space_lookup_mem(P,X,env_space(Other,S,Outer)) <=> trie_space_lookup_mem(P,X,Outer)))).
fof(trie_space_lookup_skip_path, axiom,
  ! [P,X,R,Q,Outer] : (trie_space_lookup_mem(P,X,env_path(R,Q,Outer)) <=> trie_space_lookup_mem(P,X,Outer))).
fof(trie_space_lookup_empty, axiom,
  ! [P,X] : (trie_space_lookup_mem(P,X,env_empty) <=> input_mem(P,X))).
fof(trie_env_empty, axiom,
  ! [P,Env] : (~ trie_env_mem(P,op_empty,Env))).
fof(trie_env_input, axiom,
  ! [P,X,Env] : (trie_env_mem(P,op_input(X),Env) <=> trie_space_lookup_mem(P,X,Env))).
fof(trie_env_literal, axiom,
  ! [P,X,Env] : (trie_env_mem(P,op_literal(X),Env) <=> literal_mem(P,X))).
fof(trie_env_singleton, axiom,
  ! [P,Q,Env] : (trie_env_mem(P,op_singleton(Q),Env) <=> path_env_matches(P,Q,Env))).
fof(trie_env_union, axiom,
  ! [P,A,B,Env] : (trie_env_mem(P,op_union(A,B),Env) <=> (trie_env_mem(P,A,Env) | trie_env_mem(P,B,Env)))).
fof(trie_env_intersection, axiom,
  ! [P,A,B,Env] : (trie_env_mem(P,op_intersection(A,B),Env) <=> (trie_env_mem(P,A,Env) & trie_env_mem(P,B,Env)))).
fof(trie_env_diff, axiom,
  ! [P,A,B,Env] : (trie_env_mem(P,op_diff(A,B),Env) <=> (trie_env_mem(P,A,Env) & ~ trie_env_mem(P,B,Env)))).
fof(trie_env_restriction, axiom,
  ! [P,A,B,Env] : (trie_env_mem(P,op_restriction(A,B),Env) <=> (trie_env_mem(P,A,Env) & ? [Q] : (trie_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(trie_env_raffination, axiom,
  ! [P,A,B,Env] : (trie_env_mem(P,op_raffination(A,B),Env) <=> (trie_env_mem(P,A,Env) & ~ ? [Q] : (trie_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(trie_env_product, axiom,
  ! [P,A,B,Env] : (trie_env_mem(P,op_product(A,B),Env) <=> ? [Q,R] : (trie_env_mem(Q,A,Env) & trie_env_mem(R,B,Env) & p_append(Q,R,P)))).
fof(trie_env_wrap, axiom,
  ! [P,A,Q,Env] : (trie_env_mem(P,op_wrap(A,Q),Env) <=> ? [Prefix,Tail] : (path_env_matches(Prefix,Q,Env) & trie_env_mem(Tail,A,Env) & p_append(Prefix,Tail,P)))).
fof(trie_env_unwrap, axiom,
  ! [P,A,Q,Env] : (trie_env_mem(P,op_unwrap(A,Q),Env) <=> ? [Prefix,Full] : (path_env_matches(Prefix,Q,Env) & p_append(Prefix,P,Full) & trie_env_mem(Full,A,Env)))).
fof(trie_env_tails_union, axiom,
  ! [P,A,Env] : (trie_env_mem(P,op_tails_union(A),Env) <=> ? [I] : trie_env_mem(cons(I,P),A,Env))).
fof(trie_env_tails_intersection, axiom,
  ! [P,A,Env] : (trie_env_mem(P,op_tails_intersection(A),Env) <=> ((? [I,Q] : trie_env_mem(cons(I,Q),A,Env)) & ! [I] : ((? [Q] : trie_env_mem(cons(I,Q),A,Env)) => trie_env_mem(cons(I,P),A,Env))))).
fof(trie_env_prefix_closure, axiom,
  ! [P,A,Env] : (trie_env_mem(P,op_prefix_closure(A),Env) <=> (P != nil & ? [Q] : (trie_env_mem(Q,A,Env) & p_prefix(P,Q))))).
fof(trie_env_suffix_closure, axiom,
  ! [P,A,Env] : (trie_env_mem(P,op_suffix_closure(A),Env) <=> (P != nil & ? [Q] : (trie_env_mem(Q,A,Env) & p_suffix(P,Q))))).
fof(trie_env_tails_closure, axiom,
  ! [P,A,Env] : (trie_env_mem(P,op_tails_closure(A),Env) <=> (((P = nil) & ? [Q] : trie_env_mem(Q,A,Env)) | (P != nil & ? [Q] : (trie_env_mem(Q,A,Env) & p_suffix(P,Q)))))).
fof(trie_env_iter, axiom,
  ! [P,A,Sym,Rest,Body,Env] : (trie_env_mem(P,op_iter(A,Sym,Rest,Body),Env) <=> ? [I] : ((? [Q] : trie_env_mem(cons(I,Q),A,Env)) & trie_env_mem(P,Body,env_space(Rest,op_child_env(A,I,Env),env_path(Sym,path_item(I),Env)))))).
fof(trie_env_child, axiom,
  ! [P,A,I,Captured,Env] : (trie_env_mem(P,op_child_env(A,I,Captured),Env) <=> trie_env_mem(cons(I,P),A,Captured))).
fof(trie_env_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update,Env] : (trie_env_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update),Env) <=> fold_env_sem(P,A,Initial,Acc,Sym,Rest,Body,Update,Env))).
fof(trie_env_fixpoint, axiom,
  ! [P,A,Var,Step,Env] : (trie_env_mem(P,op_fixpoint(A,Var,Step),Env) <=> (trie_env_mem(P,A,Env) | trie_env_mem(P,Step,env_space(Var,op_fixpoint(A,Var,Step),Env))))).
fof(trie_env_grounded_ps, axiom,
  ! [P,Q,Env] : (trie_env_mem(P,op_grounded_ps(Q),Env) <=> grounded_ps_env_sem(P,Q,Env))).
fof(trie_env_grounded_ss, axiom,
  ! [P,A,Env] : (trie_env_mem(P,op_grounded_ss(A),Env) <=> grounded_ss_env_sem(P,A,Env))).
fof(trie_env_range, axiom,
  ! [P,A,Start,End,Env] : (trie_env_mem(P,op_range(A,Start,End),Env) <=> (trie_env_mem(P,A,Env) & range_select_env(P,A,Env,Start,End)))).
fof(zipper_empty, axiom,
  ! [P] : (~ zipper_mem(P,op_empty))).
fof(zipper_input, axiom,
  ! [P,X] : (zipper_mem(P,op_input(X)) <=> input_mem(P,X))).
fof(zipper_literal, axiom,
  ! [P,X] : (zipper_mem(P,op_literal(X)) <=> literal_mem(P,X))).
fof(zipper_singleton, axiom,
  ! [P,Q] : (zipper_mem(P,op_singleton(Q)) <=> path_matches(P,Q))).
fof(zipper_union, axiom,
  ! [P,A,B] : (zipper_mem(P,op_union(A,B)) <=> (zipper_mem(P,A) | zipper_mem(P,B)))).
fof(zipper_intersection, axiom,
  ! [P,A,B] : (zipper_mem(P,op_intersection(A,B)) <=> (zipper_mem(P,A) & zipper_mem(P,B)))).
fof(zipper_diff, axiom,
  ! [P,A,B] : (zipper_mem(P,op_diff(A,B)) <=> (zipper_mem(P,A) & ~ zipper_mem(P,B)))).
fof(zipper_restriction, axiom,
  ! [P,A,B] : (zipper_mem(P,op_restriction(A,B)) <=> (zipper_mem(P,A) & ? [Q] : (zipper_mem(Q,B) & p_prefix(Q,P))))).
fof(zipper_raffination, axiom,
  ! [P,A,B] : (zipper_mem(P,op_raffination(A,B)) <=> (zipper_mem(P,A) & ~ ? [Q] : (zipper_mem(Q,B) & p_prefix(Q,P))))).
fof(zipper_product, axiom,
  ! [P,A,B] : (zipper_mem(P,op_product(A,B)) <=> ? [Q,R] : (zipper_mem(Q,A) & zipper_mem(R,B) & p_append(Q,R,P)))).
fof(zipper_wrap, axiom,
  ! [P,A,Q] : (zipper_mem(P,op_wrap(A,Q)) <=> ? [Prefix,Tail] : (path_matches(Prefix,Q) & zipper_mem(Tail,A) & p_append(Prefix,Tail,P)))).
fof(zipper_unwrap, axiom,
  ! [P,A,Q] : (zipper_mem(P,op_unwrap(A,Q)) <=> ? [Prefix,Full] : (path_matches(Prefix,Q) & p_append(Prefix,P,Full) & zipper_mem(Full,A)))).
fof(zipper_tails_union, axiom,
  ! [P,A] : (zipper_mem(P,op_tails_union(A)) <=> ? [I] : zipper_mem(cons(I,P),A))).
fof(zipper_tails_intersection, axiom,
  ! [P,A] : (zipper_mem(P,op_tails_intersection(A)) <=> ((? [I,Q] : zipper_mem(cons(I,Q),A)) & ! [I] : ((? [Q] : zipper_mem(cons(I,Q),A)) => zipper_mem(cons(I,P),A))))).
fof(zipper_prefix_closure, axiom,
  ! [P,A] : (zipper_mem(P,op_prefix_closure(A)) <=> (P != nil & ? [Q] : (zipper_mem(Q,A) & p_prefix(P,Q))))).
fof(zipper_suffix_closure, axiom,
  ! [P,A] : (zipper_mem(P,op_suffix_closure(A)) <=> (P != nil & ? [Q] : (zipper_mem(Q,A) & p_suffix(P,Q))))).
fof(zipper_tails_closure, axiom,
  ! [P,A] : (zipper_mem(P,op_tails_closure(A)) <=> (((P = nil) & ? [Q] : zipper_mem(Q,A)) | (P != nil & ? [Q] : (zipper_mem(Q,A) & p_suffix(P,Q)))))).
fof(zipper_iter, axiom,
  ! [P,A,Sym,Rest,Body] : (zipper_mem(P,op_iter(A,Sym,Rest,Body)) <=> zipper_env_mem(P,op_iter(A,Sym,Rest,Body),env_empty))).
fof(zipper_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (zipper_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> fold_sem(P,A,Initial,Acc,Sym,Rest,Body,Update))).
fof(zipper_fixpoint, axiom,
  ! [P,A,Var,Step] : (zipper_mem(P,op_fixpoint(A,Var,Step)) <=> zipper_env_mem(P,op_fixpoint(A,Var,Step),env_empty))).
fof(zipper_grounded_ps, axiom,
  ! [P,Q] : (zipper_mem(P,op_grounded_ps(Q)) <=> grounded_ps_sem(P,Q))).
fof(zipper_grounded_ss, axiom,
  ! [P,A] : (zipper_mem(P,op_grounded_ss(A)) <=> grounded_ss_sem(P,A))).
fof(zipper_range, axiom,
  ! [P,A,Start,End] : (zipper_mem(P,op_range(A,Start,End)) <=> zipper_env_mem(P,op_range(A,Start,End),env_empty))).
fof(zipper_space_lookup_hit, axiom,
  ! [P,X,S,Outer] : (zipper_space_lookup_mem(P,X,env_space(X,S,Outer)) <=> zipper_env_mem(P,S,Outer))).
fof(zipper_space_lookup_miss_space, axiom,
  ! [P,X,Other,S,Outer] : (X != Other => (zipper_space_lookup_mem(P,X,env_space(Other,S,Outer)) <=> zipper_space_lookup_mem(P,X,Outer)))).
fof(zipper_space_lookup_skip_path, axiom,
  ! [P,X,R,Q,Outer] : (zipper_space_lookup_mem(P,X,env_path(R,Q,Outer)) <=> zipper_space_lookup_mem(P,X,Outer))).
fof(zipper_space_lookup_empty, axiom,
  ! [P,X] : (zipper_space_lookup_mem(P,X,env_empty) <=> input_mem(P,X))).
fof(zipper_env_empty, axiom,
  ! [P,Env] : (~ zipper_env_mem(P,op_empty,Env))).
fof(zipper_env_input, axiom,
  ! [P,X,Env] : (zipper_env_mem(P,op_input(X),Env) <=> zipper_space_lookup_mem(P,X,Env))).
fof(zipper_env_literal, axiom,
  ! [P,X,Env] : (zipper_env_mem(P,op_literal(X),Env) <=> literal_mem(P,X))).
fof(zipper_env_singleton, axiom,
  ! [P,Q,Env] : (zipper_env_mem(P,op_singleton(Q),Env) <=> path_env_matches(P,Q,Env))).
fof(zipper_env_union, axiom,
  ! [P,A,B,Env] : (zipper_env_mem(P,op_union(A,B),Env) <=> (zipper_env_mem(P,A,Env) | zipper_env_mem(P,B,Env)))).
fof(zipper_env_intersection, axiom,
  ! [P,A,B,Env] : (zipper_env_mem(P,op_intersection(A,B),Env) <=> (zipper_env_mem(P,A,Env) & zipper_env_mem(P,B,Env)))).
fof(zipper_env_diff, axiom,
  ! [P,A,B,Env] : (zipper_env_mem(P,op_diff(A,B),Env) <=> (zipper_env_mem(P,A,Env) & ~ zipper_env_mem(P,B,Env)))).
fof(zipper_env_restriction, axiom,
  ! [P,A,B,Env] : (zipper_env_mem(P,op_restriction(A,B),Env) <=> (zipper_env_mem(P,A,Env) & ? [Q] : (zipper_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(zipper_env_raffination, axiom,
  ! [P,A,B,Env] : (zipper_env_mem(P,op_raffination(A,B),Env) <=> (zipper_env_mem(P,A,Env) & ~ ? [Q] : (zipper_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(zipper_env_product, axiom,
  ! [P,A,B,Env] : (zipper_env_mem(P,op_product(A,B),Env) <=> ? [Q,R] : (zipper_env_mem(Q,A,Env) & zipper_env_mem(R,B,Env) & p_append(Q,R,P)))).
fof(zipper_env_wrap, axiom,
  ! [P,A,Q,Env] : (zipper_env_mem(P,op_wrap(A,Q),Env) <=> ? [Prefix,Tail] : (path_env_matches(Prefix,Q,Env) & zipper_env_mem(Tail,A,Env) & p_append(Prefix,Tail,P)))).
fof(zipper_env_unwrap, axiom,
  ! [P,A,Q,Env] : (zipper_env_mem(P,op_unwrap(A,Q),Env) <=> ? [Prefix,Full] : (path_env_matches(Prefix,Q,Env) & p_append(Prefix,P,Full) & zipper_env_mem(Full,A,Env)))).
fof(zipper_env_tails_union, axiom,
  ! [P,A,Env] : (zipper_env_mem(P,op_tails_union(A),Env) <=> ? [I] : zipper_env_mem(cons(I,P),A,Env))).
fof(zipper_env_tails_intersection, axiom,
  ! [P,A,Env] : (zipper_env_mem(P,op_tails_intersection(A),Env) <=> ((? [I,Q] : zipper_env_mem(cons(I,Q),A,Env)) & ! [I] : ((? [Q] : zipper_env_mem(cons(I,Q),A,Env)) => zipper_env_mem(cons(I,P),A,Env))))).
fof(zipper_env_prefix_closure, axiom,
  ! [P,A,Env] : (zipper_env_mem(P,op_prefix_closure(A),Env) <=> (P != nil & ? [Q] : (zipper_env_mem(Q,A,Env) & p_prefix(P,Q))))).
fof(zipper_env_suffix_closure, axiom,
  ! [P,A,Env] : (zipper_env_mem(P,op_suffix_closure(A),Env) <=> (P != nil & ? [Q] : (zipper_env_mem(Q,A,Env) & p_suffix(P,Q))))).
fof(zipper_env_tails_closure, axiom,
  ! [P,A,Env] : (zipper_env_mem(P,op_tails_closure(A),Env) <=> (((P = nil) & ? [Q] : zipper_env_mem(Q,A,Env)) | (P != nil & ? [Q] : (zipper_env_mem(Q,A,Env) & p_suffix(P,Q)))))).
fof(zipper_env_iter, axiom,
  ! [P,A,Sym,Rest,Body,Env] : (zipper_env_mem(P,op_iter(A,Sym,Rest,Body),Env) <=> ? [I] : ((? [Q] : zipper_env_mem(cons(I,Q),A,Env)) & zipper_env_mem(P,Body,env_space(Rest,op_child_env(A,I,Env),env_path(Sym,path_item(I),Env)))))).
fof(zipper_env_child, axiom,
  ! [P,A,I,Captured,Env] : (zipper_env_mem(P,op_child_env(A,I,Captured),Env) <=> zipper_env_mem(cons(I,P),A,Captured))).
fof(zipper_env_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update,Env] : (zipper_env_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update),Env) <=> fold_env_sem(P,A,Initial,Acc,Sym,Rest,Body,Update,Env))).
fof(zipper_env_fixpoint, axiom,
  ! [P,A,Var,Step,Env] : (zipper_env_mem(P,op_fixpoint(A,Var,Step),Env) <=> (zipper_env_mem(P,A,Env) | zipper_env_mem(P,Step,env_space(Var,op_fixpoint(A,Var,Step),Env))))).
fof(zipper_env_grounded_ps, axiom,
  ! [P,Q,Env] : (zipper_env_mem(P,op_grounded_ps(Q),Env) <=> grounded_ps_env_sem(P,Q,Env))).
fof(zipper_env_grounded_ss, axiom,
  ! [P,A,Env] : (zipper_env_mem(P,op_grounded_ss(A),Env) <=> grounded_ss_env_sem(P,A,Env))).
fof(zipper_env_range, axiom,
  ! [P,A,Start,End,Env] : (zipper_env_mem(P,op_range(A,Start,End),Env) <=> (zipper_env_mem(P,A,Env) & range_select_env(P,A,Env,Start,End)))).
fof(graph_empty, axiom,
  ! [P] : (~ graph_mem(P,op_empty))).
fof(graph_input, axiom,
  ! [P,X] : (graph_mem(P,op_input(X)) <=> input_mem(P,X))).
fof(graph_literal, axiom,
  ! [P,X] : (graph_mem(P,op_literal(X)) <=> literal_mem(P,X))).
fof(graph_singleton, axiom,
  ! [P,Q] : (graph_mem(P,op_singleton(Q)) <=> path_matches(P,Q))).
fof(graph_union, axiom,
  ! [P,A,B] : (graph_mem(P,op_union(A,B)) <=> (graph_mem(P,A) | graph_mem(P,B)))).
fof(graph_intersection, axiom,
  ! [P,A,B] : (graph_mem(P,op_intersection(A,B)) <=> (graph_mem(P,A) & graph_mem(P,B)))).
fof(graph_diff, axiom,
  ! [P,A,B] : (graph_mem(P,op_diff(A,B)) <=> (graph_mem(P,A) & ~ graph_mem(P,B)))).
fof(graph_restriction, axiom,
  ! [P,A,B] : (graph_mem(P,op_restriction(A,B)) <=> (graph_mem(P,A) & ? [Q] : (graph_mem(Q,B) & p_prefix(Q,P))))).
fof(graph_raffination, axiom,
  ! [P,A,B] : (graph_mem(P,op_raffination(A,B)) <=> (graph_mem(P,A) & ~ ? [Q] : (graph_mem(Q,B) & p_prefix(Q,P))))).
fof(graph_product, axiom,
  ! [P,A,B] : (graph_mem(P,op_product(A,B)) <=> ? [Q,R] : (graph_mem(Q,A) & graph_mem(R,B) & p_append(Q,R,P)))).
fof(graph_wrap, axiom,
  ! [P,A,Q] : (graph_mem(P,op_wrap(A,Q)) <=> ? [Prefix,Tail] : (path_matches(Prefix,Q) & graph_mem(Tail,A) & p_append(Prefix,Tail,P)))).
fof(graph_unwrap, axiom,
  ! [P,A,Q] : (graph_mem(P,op_unwrap(A,Q)) <=> ? [Prefix,Full] : (path_matches(Prefix,Q) & p_append(Prefix,P,Full) & graph_mem(Full,A)))).
fof(graph_tails_union, axiom,
  ! [P,A] : (graph_mem(P,op_tails_union(A)) <=> ? [I] : graph_mem(cons(I,P),A))).
fof(graph_tails_intersection, axiom,
  ! [P,A] : (graph_mem(P,op_tails_intersection(A)) <=> ((? [I,Q] : graph_mem(cons(I,Q),A)) & ! [I] : ((? [Q] : graph_mem(cons(I,Q),A)) => graph_mem(cons(I,P),A))))).
fof(graph_prefix_closure, axiom,
  ! [P,A] : (graph_mem(P,op_prefix_closure(A)) <=> (P != nil & ? [Q] : (graph_mem(Q,A) & p_prefix(P,Q))))).
fof(graph_suffix_closure, axiom,
  ! [P,A] : (graph_mem(P,op_suffix_closure(A)) <=> (P != nil & ? [Q] : (graph_mem(Q,A) & p_suffix(P,Q))))).
fof(graph_tails_closure, axiom,
  ! [P,A] : (graph_mem(P,op_tails_closure(A)) <=> (((P = nil) & ? [Q] : graph_mem(Q,A)) | (P != nil & ? [Q] : (graph_mem(Q,A) & p_suffix(P,Q)))))).
fof(graph_iter, axiom,
  ! [P,A,Sym,Rest,Body] : (graph_mem(P,op_iter(A,Sym,Rest,Body)) <=> graph_env_mem(P,op_iter(A,Sym,Rest,Body),env_empty))).
fof(graph_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (graph_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> fold_sem(P,A,Initial,Acc,Sym,Rest,Body,Update))).
fof(graph_fixpoint, axiom,
  ! [P,A,Var,Step] : (graph_mem(P,op_fixpoint(A,Var,Step)) <=> graph_env_mem(P,op_fixpoint(A,Var,Step),env_empty))).
fof(graph_grounded_ps, axiom,
  ! [P,Q] : (graph_mem(P,op_grounded_ps(Q)) <=> grounded_ps_sem(P,Q))).
fof(graph_grounded_ss, axiom,
  ! [P,A] : (graph_mem(P,op_grounded_ss(A)) <=> grounded_ss_sem(P,A))).
fof(graph_range, axiom,
  ! [P,A,Start,End] : (graph_mem(P,op_range(A,Start,End)) <=> graph_env_mem(P,op_range(A,Start,End),env_empty))).
fof(graph_space_lookup_hit, axiom,
  ! [P,X,S,Outer] : (graph_space_lookup_mem(P,X,env_space(X,S,Outer)) <=> graph_env_mem(P,S,Outer))).
fof(graph_space_lookup_miss_space, axiom,
  ! [P,X,Other,S,Outer] : (X != Other => (graph_space_lookup_mem(P,X,env_space(Other,S,Outer)) <=> graph_space_lookup_mem(P,X,Outer)))).
fof(graph_space_lookup_skip_path, axiom,
  ! [P,X,R,Q,Outer] : (graph_space_lookup_mem(P,X,env_path(R,Q,Outer)) <=> graph_space_lookup_mem(P,X,Outer))).
fof(graph_space_lookup_empty, axiom,
  ! [P,X] : (graph_space_lookup_mem(P,X,env_empty) <=> input_mem(P,X))).
fof(graph_env_empty, axiom,
  ! [P,Env] : (~ graph_env_mem(P,op_empty,Env))).
fof(graph_env_input, axiom,
  ! [P,X,Env] : (graph_env_mem(P,op_input(X),Env) <=> graph_space_lookup_mem(P,X,Env))).
fof(graph_env_literal, axiom,
  ! [P,X,Env] : (graph_env_mem(P,op_literal(X),Env) <=> literal_mem(P,X))).
fof(graph_env_singleton, axiom,
  ! [P,Q,Env] : (graph_env_mem(P,op_singleton(Q),Env) <=> path_env_matches(P,Q,Env))).
fof(graph_env_union, axiom,
  ! [P,A,B,Env] : (graph_env_mem(P,op_union(A,B),Env) <=> (graph_env_mem(P,A,Env) | graph_env_mem(P,B,Env)))).
fof(graph_env_intersection, axiom,
  ! [P,A,B,Env] : (graph_env_mem(P,op_intersection(A,B),Env) <=> (graph_env_mem(P,A,Env) & graph_env_mem(P,B,Env)))).
fof(graph_env_diff, axiom,
  ! [P,A,B,Env] : (graph_env_mem(P,op_diff(A,B),Env) <=> (graph_env_mem(P,A,Env) & ~ graph_env_mem(P,B,Env)))).
fof(graph_env_restriction, axiom,
  ! [P,A,B,Env] : (graph_env_mem(P,op_restriction(A,B),Env) <=> (graph_env_mem(P,A,Env) & ? [Q] : (graph_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(graph_env_raffination, axiom,
  ! [P,A,B,Env] : (graph_env_mem(P,op_raffination(A,B),Env) <=> (graph_env_mem(P,A,Env) & ~ ? [Q] : (graph_env_mem(Q,B,Env) & p_prefix(Q,P))))).
fof(graph_env_product, axiom,
  ! [P,A,B,Env] : (graph_env_mem(P,op_product(A,B),Env) <=> ? [Q,R] : (graph_env_mem(Q,A,Env) & graph_env_mem(R,B,Env) & p_append(Q,R,P)))).
fof(graph_env_wrap, axiom,
  ! [P,A,Q,Env] : (graph_env_mem(P,op_wrap(A,Q),Env) <=> ? [Prefix,Tail] : (path_env_matches(Prefix,Q,Env) & graph_env_mem(Tail,A,Env) & p_append(Prefix,Tail,P)))).
fof(graph_env_unwrap, axiom,
  ! [P,A,Q,Env] : (graph_env_mem(P,op_unwrap(A,Q),Env) <=> ? [Prefix,Full] : (path_env_matches(Prefix,Q,Env) & p_append(Prefix,P,Full) & graph_env_mem(Full,A,Env)))).
fof(graph_env_tails_union, axiom,
  ! [P,A,Env] : (graph_env_mem(P,op_tails_union(A),Env) <=> ? [I] : graph_env_mem(cons(I,P),A,Env))).
fof(graph_env_tails_intersection, axiom,
  ! [P,A,Env] : (graph_env_mem(P,op_tails_intersection(A),Env) <=> ((? [I,Q] : graph_env_mem(cons(I,Q),A,Env)) & ! [I] : ((? [Q] : graph_env_mem(cons(I,Q),A,Env)) => graph_env_mem(cons(I,P),A,Env))))).
fof(graph_env_prefix_closure, axiom,
  ! [P,A,Env] : (graph_env_mem(P,op_prefix_closure(A),Env) <=> (P != nil & ? [Q] : (graph_env_mem(Q,A,Env) & p_prefix(P,Q))))).
fof(graph_env_suffix_closure, axiom,
  ! [P,A,Env] : (graph_env_mem(P,op_suffix_closure(A),Env) <=> (P != nil & ? [Q] : (graph_env_mem(Q,A,Env) & p_suffix(P,Q))))).
fof(graph_env_tails_closure, axiom,
  ! [P,A,Env] : (graph_env_mem(P,op_tails_closure(A),Env) <=> (((P = nil) & ? [Q] : graph_env_mem(Q,A,Env)) | (P != nil & ? [Q] : (graph_env_mem(Q,A,Env) & p_suffix(P,Q)))))).
fof(graph_env_iter, axiom,
  ! [P,A,Sym,Rest,Body,Env] : (graph_env_mem(P,op_iter(A,Sym,Rest,Body),Env) <=> ? [I] : ((? [Q] : graph_env_mem(cons(I,Q),A,Env)) & graph_env_mem(P,Body,env_space(Rest,op_child_env(A,I,Env),env_path(Sym,path_item(I),Env)))))).
fof(graph_env_child, axiom,
  ! [P,A,I,Captured,Env] : (graph_env_mem(P,op_child_env(A,I,Captured),Env) <=> graph_env_mem(cons(I,P),A,Captured))).
fof(graph_env_fold, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update,Env] : (graph_env_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update),Env) <=> fold_env_sem(P,A,Initial,Acc,Sym,Rest,Body,Update,Env))).
fof(graph_env_fixpoint, axiom,
  ! [P,A,Var,Step,Env] : (graph_env_mem(P,op_fixpoint(A,Var,Step),Env) <=> (graph_env_mem(P,A,Env) | graph_env_mem(P,Step,env_space(Var,op_fixpoint(A,Var,Step),Env))))).
fof(graph_env_grounded_ps, axiom,
  ! [P,Q,Env] : (graph_env_mem(P,op_grounded_ps(Q),Env) <=> grounded_ps_env_sem(P,Q,Env))).
fof(graph_env_grounded_ss, axiom,
  ! [P,A,Env] : (graph_env_mem(P,op_grounded_ss(A),Env) <=> grounded_ss_env_sem(P,A,Env))).
fof(graph_env_range, axiom,
  ! [P,A,Start,End,Env] : (graph_env_mem(P,op_range(A,Start,End),Env) <=> (graph_env_mem(P,A,Env) & range_select_env(P,A,Env,Start,End)))).

% Per-constructor implementation equivalence lemmas. These are the ATP
% bias for large open programs: each backend proves one constructor
% against source semantics, then full program DAGs compose those lemmas.
fof(optimized_source_empty_source_equiv, axiom,
  ! [P] : (source_mem(P,op_empty) <=> optimized_source_mem(P,op_empty))).
fof(optimized_source_input_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_input(X)) <=> optimized_source_mem(P,op_input(X)))).
fof(optimized_source_literal_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_literal(X)) <=> optimized_source_mem(P,op_literal(X)))).
fof(optimized_source_singleton_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_singleton(Q)) <=> optimized_source_mem(P,op_singleton(Q)))).
fof(optimized_source_union_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_union(A,B)) <=> optimized_source_mem(P,op_union(A,B)))).
fof(optimized_source_intersection_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_intersection(A,B)) <=> optimized_source_mem(P,op_intersection(A,B)))).
fof(optimized_source_diff_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_diff(A,B)) <=> optimized_source_mem(P,op_diff(A,B)))).
fof(optimized_source_restriction_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_restriction(A,B)) <=> optimized_source_mem(P,op_restriction(A,B)))).
fof(optimized_source_raffination_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_raffination(A,B)) <=> optimized_source_mem(P,op_raffination(A,B)))).
fof(optimized_source_product_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_product(A,B)) <=> optimized_source_mem(P,op_product(A,B)))).
fof(optimized_source_wrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_wrap(A,Q)) <=> optimized_source_mem(P,op_wrap(A,Q)))).
fof(optimized_source_unwrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_unwrap(A,Q)) <=> optimized_source_mem(P,op_unwrap(A,Q)))).
fof(optimized_source_tails_union_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_union(A)) <=> optimized_source_mem(P,op_tails_union(A)))).
fof(optimized_source_tails_intersection_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_intersection(A)) <=> optimized_source_mem(P,op_tails_intersection(A)))).
fof(optimized_source_prefix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_prefix_closure(A)) <=> optimized_source_mem(P,op_prefix_closure(A)))).
fof(optimized_source_suffix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_suffix_closure(A)) <=> optimized_source_mem(P,op_suffix_closure(A)))).
fof(optimized_source_tails_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_closure(A)) <=> optimized_source_mem(P,op_tails_closure(A)))).
fof(optimized_source_iter_source_equiv, axiom,
  ! [P,A,Sym,Rest,Body] : (source_mem(P,op_iter(A,Sym,Rest,Body)) <=> optimized_source_mem(P,op_iter(A,Sym,Rest,Body)))).
fof(optimized_source_fold_source_equiv, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (source_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> optimized_source_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)))).
fof(optimized_source_fixpoint_source_equiv, axiom,
  ! [P,A,Var,Step] : (source_mem(P,op_fixpoint(A,Var,Step)) <=> optimized_source_mem(P,op_fixpoint(A,Var,Step)))).
fof(optimized_source_grounded_ps_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_grounded_ps(Q)) <=> optimized_source_mem(P,op_grounded_ps(Q)))).
fof(optimized_source_grounded_ss_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_grounded_ss(A)) <=> optimized_source_mem(P,op_grounded_ss(A)))).
fof(optimized_source_range_source_equiv, axiom,
  ! [P,A,Start,End] : (source_mem(P,op_range(A,Start,End)) <=> optimized_source_mem(P,op_range(A,Start,End)))).
fof(optimized_source_call_source_equiv, axiom,
  ! [P,R,Refs,Args] : (source_mem(P,op_call(R,Refs,Args)) <=> optimized_source_mem(P,op_call(R,Refs,Args)))).
fof(trie_empty_source_equiv, axiom,
  ! [P] : (source_mem(P,op_empty) <=> trie_mem(P,op_empty))).
fof(trie_input_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_input(X)) <=> trie_mem(P,op_input(X)))).
fof(trie_literal_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_literal(X)) <=> trie_mem(P,op_literal(X)))).
fof(trie_singleton_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_singleton(Q)) <=> trie_mem(P,op_singleton(Q)))).
fof(trie_union_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_union(A,B)) <=> trie_mem(P,op_union(A,B)))).
fof(trie_intersection_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_intersection(A,B)) <=> trie_mem(P,op_intersection(A,B)))).
fof(trie_diff_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_diff(A,B)) <=> trie_mem(P,op_diff(A,B)))).
fof(trie_restriction_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_restriction(A,B)) <=> trie_mem(P,op_restriction(A,B)))).
fof(trie_raffination_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_raffination(A,B)) <=> trie_mem(P,op_raffination(A,B)))).
fof(trie_product_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_product(A,B)) <=> trie_mem(P,op_product(A,B)))).
fof(trie_wrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_wrap(A,Q)) <=> trie_mem(P,op_wrap(A,Q)))).
fof(trie_unwrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_unwrap(A,Q)) <=> trie_mem(P,op_unwrap(A,Q)))).
fof(trie_tails_union_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_union(A)) <=> trie_mem(P,op_tails_union(A)))).
fof(trie_tails_intersection_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_intersection(A)) <=> trie_mem(P,op_tails_intersection(A)))).
fof(trie_prefix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_prefix_closure(A)) <=> trie_mem(P,op_prefix_closure(A)))).
fof(trie_suffix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_suffix_closure(A)) <=> trie_mem(P,op_suffix_closure(A)))).
fof(trie_tails_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_closure(A)) <=> trie_mem(P,op_tails_closure(A)))).
fof(trie_iter_source_equiv, axiom,
  ! [P,A,Sym,Rest,Body] : (source_mem(P,op_iter(A,Sym,Rest,Body)) <=> trie_mem(P,op_iter(A,Sym,Rest,Body)))).
fof(trie_fold_source_equiv, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (source_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> trie_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)))).
fof(trie_fixpoint_source_equiv, axiom,
  ! [P,A,Var,Step] : (source_mem(P,op_fixpoint(A,Var,Step)) <=> trie_mem(P,op_fixpoint(A,Var,Step)))).
fof(trie_grounded_ps_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_grounded_ps(Q)) <=> trie_mem(P,op_grounded_ps(Q)))).
fof(trie_grounded_ss_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_grounded_ss(A)) <=> trie_mem(P,op_grounded_ss(A)))).
fof(trie_range_source_equiv, axiom,
  ! [P,A,Start,End] : (source_mem(P,op_range(A,Start,End)) <=> trie_mem(P,op_range(A,Start,End)))).
fof(trie_call_source_equiv, axiom,
  ! [P,R,Refs,Args] : (source_mem(P,op_call(R,Refs,Args)) <=> trie_mem(P,op_call(R,Refs,Args)))).
fof(zipper_empty_source_equiv, axiom,
  ! [P] : (source_mem(P,op_empty) <=> zipper_mem(P,op_empty))).
fof(zipper_input_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_input(X)) <=> zipper_mem(P,op_input(X)))).
fof(zipper_literal_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_literal(X)) <=> zipper_mem(P,op_literal(X)))).
fof(zipper_singleton_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_singleton(Q)) <=> zipper_mem(P,op_singleton(Q)))).
fof(zipper_union_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_union(A,B)) <=> zipper_mem(P,op_union(A,B)))).
fof(zipper_intersection_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_intersection(A,B)) <=> zipper_mem(P,op_intersection(A,B)))).
fof(zipper_diff_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_diff(A,B)) <=> zipper_mem(P,op_diff(A,B)))).
fof(zipper_restriction_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_restriction(A,B)) <=> zipper_mem(P,op_restriction(A,B)))).
fof(zipper_raffination_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_raffination(A,B)) <=> zipper_mem(P,op_raffination(A,B)))).
fof(zipper_product_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_product(A,B)) <=> zipper_mem(P,op_product(A,B)))).
fof(zipper_wrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_wrap(A,Q)) <=> zipper_mem(P,op_wrap(A,Q)))).
fof(zipper_unwrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_unwrap(A,Q)) <=> zipper_mem(P,op_unwrap(A,Q)))).
fof(zipper_tails_union_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_union(A)) <=> zipper_mem(P,op_tails_union(A)))).
fof(zipper_tails_intersection_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_intersection(A)) <=> zipper_mem(P,op_tails_intersection(A)))).
fof(zipper_prefix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_prefix_closure(A)) <=> zipper_mem(P,op_prefix_closure(A)))).
fof(zipper_suffix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_suffix_closure(A)) <=> zipper_mem(P,op_suffix_closure(A)))).
fof(zipper_tails_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_closure(A)) <=> zipper_mem(P,op_tails_closure(A)))).
fof(zipper_iter_source_equiv, axiom,
  ! [P,A,Sym,Rest,Body] : (source_mem(P,op_iter(A,Sym,Rest,Body)) <=> zipper_mem(P,op_iter(A,Sym,Rest,Body)))).
fof(zipper_fold_source_equiv, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (source_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> zipper_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)))).
fof(zipper_fixpoint_source_equiv, axiom,
  ! [P,A,Var,Step] : (source_mem(P,op_fixpoint(A,Var,Step)) <=> zipper_mem(P,op_fixpoint(A,Var,Step)))).
fof(zipper_grounded_ps_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_grounded_ps(Q)) <=> zipper_mem(P,op_grounded_ps(Q)))).
fof(zipper_grounded_ss_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_grounded_ss(A)) <=> zipper_mem(P,op_grounded_ss(A)))).
fof(zipper_range_source_equiv, axiom,
  ! [P,A,Start,End] : (source_mem(P,op_range(A,Start,End)) <=> zipper_mem(P,op_range(A,Start,End)))).
fof(zipper_call_source_equiv, axiom,
  ! [P,R,Refs,Args] : (source_mem(P,op_call(R,Refs,Args)) <=> zipper_mem(P,op_call(R,Refs,Args)))).
fof(graph_empty_source_equiv, axiom,
  ! [P] : (source_mem(P,op_empty) <=> graph_mem(P,op_empty))).
fof(graph_input_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_input(X)) <=> graph_mem(P,op_input(X)))).
fof(graph_literal_source_equiv, axiom,
  ! [P,X] : (source_mem(P,op_literal(X)) <=> graph_mem(P,op_literal(X)))).
fof(graph_singleton_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_singleton(Q)) <=> graph_mem(P,op_singleton(Q)))).
fof(graph_union_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_union(A,B)) <=> graph_mem(P,op_union(A,B)))).
fof(graph_intersection_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_intersection(A,B)) <=> graph_mem(P,op_intersection(A,B)))).
fof(graph_diff_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_diff(A,B)) <=> graph_mem(P,op_diff(A,B)))).
fof(graph_restriction_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_restriction(A,B)) <=> graph_mem(P,op_restriction(A,B)))).
fof(graph_raffination_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_raffination(A,B)) <=> graph_mem(P,op_raffination(A,B)))).
fof(graph_product_source_equiv, axiom,
  ! [P,A,B] : (source_mem(P,op_product(A,B)) <=> graph_mem(P,op_product(A,B)))).
fof(graph_wrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_wrap(A,Q)) <=> graph_mem(P,op_wrap(A,Q)))).
fof(graph_unwrap_source_equiv, axiom,
  ! [P,A,Q] : (source_mem(P,op_unwrap(A,Q)) <=> graph_mem(P,op_unwrap(A,Q)))).
fof(graph_tails_union_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_union(A)) <=> graph_mem(P,op_tails_union(A)))).
fof(graph_tails_intersection_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_intersection(A)) <=> graph_mem(P,op_tails_intersection(A)))).
fof(graph_prefix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_prefix_closure(A)) <=> graph_mem(P,op_prefix_closure(A)))).
fof(graph_suffix_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_suffix_closure(A)) <=> graph_mem(P,op_suffix_closure(A)))).
fof(graph_tails_closure_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_tails_closure(A)) <=> graph_mem(P,op_tails_closure(A)))).
fof(graph_iter_source_equiv, axiom,
  ! [P,A,Sym,Rest,Body] : (source_mem(P,op_iter(A,Sym,Rest,Body)) <=> graph_mem(P,op_iter(A,Sym,Rest,Body)))).
fof(graph_fold_source_equiv, axiom,
  ! [P,A,Initial,Acc,Sym,Rest,Body,Update] : (source_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)) <=> graph_mem(P,op_fold(A,Initial,Acc,Sym,Rest,Body,Update)))).
fof(graph_fixpoint_source_equiv, axiom,
  ! [P,A,Var,Step] : (source_mem(P,op_fixpoint(A,Var,Step)) <=> graph_mem(P,op_fixpoint(A,Var,Step)))).
fof(graph_grounded_ps_source_equiv, axiom,
  ! [P,Q] : (source_mem(P,op_grounded_ps(Q)) <=> graph_mem(P,op_grounded_ps(Q)))).
fof(graph_grounded_ss_source_equiv, axiom,
  ! [P,A] : (source_mem(P,op_grounded_ss(A)) <=> graph_mem(P,op_grounded_ss(A)))).
fof(graph_range_source_equiv, axiom,
  ! [P,A,Start,End] : (source_mem(P,op_range(A,Start,End)) <=> graph_mem(P,op_range(A,Start,End)))).
fof(graph_call_source_equiv, axiom,
  ! [P,R,Refs,Args] : (source_mem(P,op_call(R,Refs,Args)) <=> graph_mem(P,op_call(R,Refs,Args)))).




fof(full_program_term_0, axiom, fp_2 = op_input(a6564676573)).
fof(full_program_term_1, axiom, fp_4 = op_input(a7363635f726561636861626c65)).
fof(full_program_term_2, axiom, fp_9 = op_input(a7363635f6e65696768626f7273)).
fof(full_program_term_3, axiom, fp_8 = op_restriction(fp_4,fp_9)).
fof(full_program_term_4, axiom, fp_7 = op_tails_union(fp_8)).
fof(full_program_term_5, axiom, fp_6 = op_wrap(fp_7,path_ref(a7363635f66726f6d))).
fof(full_program_term_6, axiom, fp_5 = op_iter(fp_4,a7363635f66726f6d,a7363635f6e65696768626f7273,fp_6)).
fof(full_program_term_7, axiom, fp_3 = op_union(fp_4,fp_5)).
fof(full_program_term_8, axiom, fp_1 = op_fixpoint(fp_2,a7363635f726561636861626c65,fp_3)).
fof(full_program_term_9, axiom, fp_12 = op_singleton(path_concat(path_ref(a7363635f746172676574),path_ref(a7363635f66726f6d)))).
fof(full_program_term_10, axiom, fp_11 = op_iter(fp_9,a7363635f746172676574,a7363635f7461726765745f72657374,fp_12)).
fof(full_program_term_11, axiom, fp_10 = op_iter(fp_1,a7363635f66726f6d,a7363635f6e65696768626f7273,fp_11)).
fof(full_program_term_12, axiom, fp_0 = op_intersection(fp_1,fp_10)).

fof(program_root, axiom, program_root = fp_0).

fof(conj, conjecture,
  ! [P] : (
    (source_mem(P,program_root) <=> optimized_source_mem(P,program_root)) &
    (source_mem(P,program_root) <=> trie_mem(P,program_root)) &
    (source_mem(P,program_root) <=> zipper_mem(P,program_root)) &
    (source_mem(P,program_root) <=> graph_mem(P,program_root))
  )
).
