% Generated by morkl.CornerstoneProofArtifactMain
% scc:trie_vs_reference
% Trie evaluator output equals reference set evaluator output.

fof(lhs_complete, axiom, ! [P] : (p_mem(P,s7363635f747269655f76735f7265666572656e63655f6c6873) <=> (P = cons(s61,cons(s61,nil)) | P = cons(s61,cons(s62,nil)) | P = cons(s62,cons(s61,nil)) | P = cons(s62,cons(s62,nil)) | P = cons(s63,cons(s63,nil)) | P = cons(s63,cons(s64,nil)) | P = cons(s64,cons(s63,nil)) | P = cons(s64,cons(s64,nil))))).
fof(rhs_complete, axiom, ! [P] : (p_mem(P,s7363635f747269655f76735f7265666572656e63655f726873) <=> (P = cons(s61,cons(s61,nil)) | P = cons(s61,cons(s62,nil)) | P = cons(s62,cons(s61,nil)) | P = cons(s62,cons(s62,nil)) | P = cons(s63,cons(s63,nil)) | P = cons(s63,cons(s64,nil)) | P = cons(s64,cons(s63,nil)) | P = cons(s64,cons(s64,nil))))).

fof(conj, conjecture, ! [P] : (p_mem(P,s7363635f747269655f76735f7265666572656e63655f6c6873) <=> p_mem(P,s7363635f747269655f76735f7265666572656e63655f726873))).
