package morkl

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path as JPath, Paths}

object IllustrativeEggArtifacts:
  val PreludeEnd = "; END GENERATED CORE PRELUDE"

  val corePrelude: String =
    s"""; Generated by morkl.IllustrativeEggArtifacts.
       |; Shared, executable semantics for the illustrative core and zipper files.
       |; The comprehensive operational model lives in zipper-descend.egg.
       |
       |(datatype Path
       |  (Eps)
       |  (Item String)
       |  (Concat Path Path))
       |
       |(datatype Space
       |  (Empty)
       |  (Singleton Path)
       |  (Union Space Space)
       |  (Intersection Space Space)
       |  (Subtraction Space Space)
       |  (Product Space Space)
       |  (Wrap Path Space)
       |  (Unwrap Space Path)
       |  (Restriction Space Space)
       |  (Raffination Space Space)
       |  (TailsUnion Space)
       |  (TailsIntersection Space)
       |  (Head Space)
       |  (PrefixClosure Space)
       |  (SuffixClosure Space)
       |  (TailsClosure Space)
       |  (BoundHead)
       |  (BoundTail)
       |  (Static Space)
       |  (Instantiate Space Path Space)
       |  (Iteration Space Space))
       |
       |; Paths are words in a free monoid. Right association is the normal form.
       |(rewrite (Concat (Eps) p) p)
       |(rewrite (Concat p (Eps)) p)
       |(rewrite (Concat (Concat p q) r) (Concat p (Concat q r)))
       |
       |; Finite-set laws. Commutativity is safe here because Space has unit values,
       |; not payloads requiring a merge policy.
       |(rewrite (Union (Empty) x) x)
       |(rewrite (Union x (Empty)) x)
       |(rewrite (Union x x) x)
       |(rewrite (Union x y) (Union y x))
       |(rewrite (Union (Union x y) z) (Union x (Union y z)))
       |
       |(rewrite (Intersection (Empty) x) (Empty))
       |(rewrite (Intersection x (Empty)) (Empty))
       |(rewrite (Intersection x x) x)
       |(rewrite (Intersection x y) (Intersection y x))
       |(rewrite (Intersection (Singleton p) (Singleton q)) (Empty) :when ((!= p q)))
       |(rewrite (Intersection (Union x y) z)
       |  (Union (Intersection x z) (Intersection y z)))
       |
       |(rewrite (Subtraction (Empty) x) (Empty))
       |(rewrite (Subtraction x (Empty)) x)
       |(rewrite (Subtraction x x) (Empty))
       |(rewrite (Subtraction (Singleton p) (Singleton q)) (Singleton p) :when ((!= p q)))
       |(rewrite (Subtraction (Union x y) z)
       |  (Union (Subtraction x z) (Subtraction y z)))
       |(rewrite (Subtraction x (Union y z))
       |  (Subtraction (Subtraction x y) z))
       |
       |; Language product and prefix navigation.
       |(rewrite (Product (Empty) x) (Empty))
       |(rewrite (Product x (Empty)) (Empty))
       |(rewrite (Product (Singleton p) (Singleton q)) (Singleton (Concat p q)))
       |(rewrite (Product (Union x y) z) (Union (Product x z) (Product y z)))
       |(rewrite (Product x (Union y z)) (Union (Product x y) (Product x z)))
       |
       |(rewrite (Wrap p (Empty)) (Empty))
       |(rewrite (Wrap (Eps) x) x)
       |(rewrite (Wrap p (Singleton q)) (Singleton (Concat p q)))
       |(rewrite (Wrap p (Union x y)) (Union (Wrap p x) (Wrap p y)))
       |
       |(rewrite (Unwrap (Empty) p) (Empty))
       |(rewrite (Unwrap x (Eps)) x)
       |(rewrite (Unwrap (Wrap p x) p) x)
       |(rewrite (Unwrap (Wrap (Item other) x) (Item item)) (Empty)
       |  :when ((!= item other)))
       |(rewrite (Unwrap (Union x y) p) (Union (Unwrap x p) (Unwrap y p)))
       |(rewrite (Unwrap (Singleton (Eps)) (Item item)) (Empty))
       |(rewrite (Unwrap (Singleton (Item item)) (Item item)) (Singleton (Eps)))
       |(rewrite (Unwrap (Singleton (Item other)) (Item item)) (Empty)
       |  :when ((!= item other)))
       |(rewrite (Unwrap (Singleton (Concat (Item item) rest)) (Item item))
       |  (Singleton rest))
       |(rewrite (Unwrap (Singleton (Concat (Item other) rest)) (Item item)) (Empty)
       |  :when ((!= item other)))
       |(rewrite (Unwrap x (Concat (Item item) rest))
       |  (Unwrap (Unwrap x (Item item)) rest))
       |
       |(rewrite (Restriction x (Empty)) (Empty))
       |(rewrite (Restriction x (Singleton (Eps))) x)
       |(rewrite (Restriction x (Union p q))
       |  (Union (Restriction x p) (Restriction x q)))
       |(rewrite (Restriction x (Singleton p)) (Wrap p (Unwrap x p)))
       |(rewrite (Raffination x prefixes)
       |  (Subtraction x (Restriction x prefixes)))
       |
       |; First-level projections and finite closures.
       |(rewrite (TailsUnion (Empty)) (Empty))
       |(rewrite (TailsUnion (Union x y)) (Union (TailsUnion x) (TailsUnion y)))
       |(rewrite (TailsUnion (Singleton (Eps))) (Empty))
       |(rewrite (TailsUnion (Singleton (Item item))) (Singleton (Eps)))
       |(rewrite (TailsUnion (Singleton (Concat (Item item) rest))) (Singleton rest))
       |
       |(rewrite (Head (Empty)) (Empty))
       |(rewrite (Head (Union x y)) (Union (Head x) (Head y)))
       |(rewrite (Head (Singleton (Eps))) (Empty))
       |(rewrite (Head (Singleton (Item item))) (Singleton (Item item)))
       |(rewrite (Head (Singleton (Concat (Item item) rest))) (Singleton (Item item)))
       |
       |; These TailsIntersection rules are exact closed frontiers of cardinality
       |; one or two. The arbitrary-cardinality scheduler has a separate generated
       |; artifact and an unbounded closed-frontier theorem.
       |(rewrite (TailsIntersection (Empty)) (Empty))
       |(rewrite (TailsIntersection (Wrap (Item item) tails)) tails)
       |(rewrite
       |  (TailsIntersection
       |    (Union (Wrap (Item item) left) (Wrap (Item item) right)))
       |  (Union left right))
       |(rewrite
       |  (TailsIntersection
       |    (Union (Wrap (Item left-head) left) (Wrap (Item right-head) right)))
       |  (Intersection left right)
       |  :when ((!= left-head right-head)))
       |
       |(rewrite (PrefixClosure (Empty)) (Empty))
       |(rewrite (PrefixClosure (Union x y))
       |  (Union (PrefixClosure x) (PrefixClosure y)))
       |(rewrite (PrefixClosure (Singleton (Eps))) (Empty))
       |(rewrite (PrefixClosure (Singleton (Item item))) (Singleton (Item item)))
       |(rewrite (PrefixClosure (Singleton (Concat (Item item) rest)))
       |  (Union
       |    (Singleton (Item item))
       |    (Wrap (Item item) (PrefixClosure (Singleton rest)))))
       |
       |(rewrite (SuffixClosure (Empty)) (Empty))
       |(rewrite (SuffixClosure (Union x y))
       |  (Union (SuffixClosure x) (SuffixClosure y)))
       |(rewrite (SuffixClosure (Singleton (Eps))) (Empty))
       |(rewrite (SuffixClosure (Singleton (Item item))) (Singleton (Item item)))
       |(rewrite (SuffixClosure (Singleton (Concat (Item item) rest)))
       |  (Union
       |    (Singleton (Concat (Item item) rest))
       |    (SuffixClosure (Singleton rest))))
       |
       |(rewrite (TailsClosure (Empty)) (Empty))
       |(rewrite (TailsClosure (Union x y))
       |  (Union (TailsClosure x) (TailsClosure y)))
       |(rewrite (TailsClosure (Singleton p))
       |  (Union (Singleton (Eps)) (SuffixClosure (Singleton p))))
       |
       |; A general iteration body is represented by bound leaves plus structural
       |; substitution. Static is a proof marker for binder-independent subtrees.
       |(rewrite (Instantiate (BoundHead) head tail) (Singleton head))
       |(rewrite (Instantiate (BoundTail) head tail) tail)
       |(rewrite (Instantiate (Static body) head tail) body)
       |(rewrite (Instantiate (Empty) head tail) (Empty))
       |(rewrite (Instantiate (Singleton p) head tail) (Singleton p))
       |(rewrite (Instantiate (Union x y) head tail)
       |  (Union (Instantiate x head tail) (Instantiate y head tail)))
       |(rewrite (Instantiate (Intersection x y) head tail)
       |  (Intersection (Instantiate x head tail) (Instantiate y head tail)))
       |(rewrite (Instantiate (Subtraction x y) head tail)
       |  (Subtraction (Instantiate x head tail) (Instantiate y head tail)))
       |(rewrite (Instantiate (Product x y) head tail)
       |  (Product (Instantiate x head tail) (Instantiate y head tail)))
       |(rewrite (Instantiate (Wrap p x) head tail)
       |  (Wrap p (Instantiate x head tail)))
       |(rewrite (Instantiate (Unwrap x p) head tail)
       |  (Unwrap (Instantiate x head tail) p))
       |(rewrite (Instantiate (Restriction x y) head tail)
       |  (Restriction (Instantiate x head tail) (Instantiate y head tail)))
       |(rewrite (Instantiate (Raffination x y) head tail)
       |  (Raffination (Instantiate x head tail) (Instantiate y head tail)))
       |(rewrite (Instantiate (TailsUnion x) head tail)
       |  (TailsUnion (Instantiate x head tail)))
       |(rewrite (Instantiate (TailsIntersection x) head tail)
       |  (TailsIntersection (Instantiate x head tail)))
       |(rewrite (Instantiate (Head x) head tail) (Head (Instantiate x head tail)))
       |(rewrite (Instantiate (PrefixClosure x) head tail)
       |  (PrefixClosure (Instantiate x head tail)))
       |(rewrite (Instantiate (SuffixClosure x) head tail)
       |  (SuffixClosure (Instantiate x head tail)))
       |(rewrite (Instantiate (TailsClosure x) head tail)
       |  (TailsClosure (Instantiate x head tail)))
       |
       |(rewrite (Iteration (Empty) body) (Empty))
       |(rewrite (Iteration (Wrap (Item head) tails) body)
       |  (Instantiate body (Item head) tails))
       |(rewrite
       |  (Iteration
       |    (Union (Wrap (Item head) left) (Wrap (Item head) right))
       |    body)
       |  (Instantiate body (Item head) (Union left right)))
       |(rewrite
       |  (Iteration
       |    (Union (Wrap (Item left-head) left) (Wrap (Item right-head) right))
       |    body)
       |  (Union
       |    (Instantiate body (Item left-head) left)
       |    (Instantiate body (Item right-head) right))
       |  :when ((!= left-head right-head)))
       |
       |$PreludeEnd""".stripMargin

  private val fixtures: String =
    """(let $a (Item "a"))
      |(let $b (Item "b"))
      |(let $c (Item "c"))
      |(let $q (Item "q"))
      |(let $zero (Item "0"))
      |(let $one (Item "1"))
      |(let $two (Item "2"))
      |(let $eps (Singleton (Eps)))
      |(let $sa (Singleton $a))
      |(let $sb (Singleton $b))
      |(let $sc (Singleton $c))
      |(let $sq (Singleton $q))
      |(let $s0 (Singleton $zero))
      |(let $s1 (Singleton $one))
      |(let $s2 (Singleton $two))
      |(let $sab (Singleton (Concat $a $b)))
      |(let $sabc (Singleton (Concat $a (Concat $b $c))))
      |(let $a-tails (Union $s0 $s1))
      |(let $b-tails (Union $s0 $s2))
      |(let $rows
      |  (Union (Wrap $a $a-tails) (Wrap $b $b-tails)))
      |""".stripMargin

  val formalProgram: String =
    s"""$corePrelude
       |
       |; formal.egg: readable checks for the finite path-set kernel.
       |; These checks normalize concrete closed terms. Unbounded laws are generated
       |; separately from ProofArtifacts.scala and discharged by Vampire.
       |
       |$fixtures
       |(let $$product
       |  (Product (Union $$sa $$sb) (Union $$s0 $$s1)))
       |(let $$product-expected
       |  (Union
       |    (Singleton (Concat $$a $$zero))
       |    (Union
       |      (Singleton (Concat $$a $$one))
       |      (Union
       |        (Singleton (Concat $$b $$zero))
       |        (Singleton (Concat $$b $$one))))))
       |(let $$prefixes-abc
       |  (Union $$sa (Union $$sab $$sabc)))
       |(let $$suffixes-abc
       |  (Union $$sabc (Union (Singleton (Concat $$b $$c)) $$sc)))
       |(let $$reconstruct-body (Product (BoundHead) (BoundTail)))
       |(let $$iteration-reconstruct (Iteration $$rows $$reconstruct-body))
       |(let $$iteration-tails (Iteration $$rows (BoundTail)))
       |(let $$iteration-static (Iteration $$rows (Static $$sq)))
       |(let $$iteration-static-union
       |  (Iteration $$rows (Union (Static $$sq) $$reconstruct-body)))
       |(let $$unwrap-wrapped-a (Unwrap (Wrap $$a $$a-tails) $$a))
       |(let $$unwrap-wrapped-b (Unwrap (Wrap $$b $$b-tails) $$a))
       |(let $$unwrap-a (Unwrap $$rows $$a))
       |(let $$restrict-a (Restriction $$rows $$sa))
       |(let $$raffinate-a (Raffination $$rows $$sa))
       |(let $$tails-union (TailsUnion $$rows))
       |(let $$tails-intersection (TailsIntersection $$rows))
       |(let $$heads (Head $$rows))
       |(let $$prefix-closure (PrefixClosure $$sabc))
       |(let $$suffix-closure (SuffixClosure $$sabc))
       |(let $$tails-closure (TailsClosure $$sabc))
       |
       |(run 24)
       |
       |; Indexed navigation and prefix-cylinder selection.
       |(check (= $$unwrap-wrapped-a $$a-tails))
       |(check (= $$unwrap-wrapped-b (Empty)))
       |(check (= $$unwrap-a $$a-tails))
       |(check (= $$restrict-a (Wrap $$a $$a-tails)))
       |(check (= $$raffinate-a (Wrap $$b $$b-tails)))
       |
       |; Existential and universal first-level projection.
       |(check (= $$tails-union (Union $$s0 (Union $$s1 $$s2))))
       |(check (= $$tails-intersection $$s0))
       |(check (= $$heads (Union $$sa $$sb)))
       |
       |; Finite-language multiplication and closures.
       |(check (= $$product $$product-expected))
       |(check (= $$prefix-closure $$prefixes-abc))
       |(check (= $$suffix-closure $$suffixes-abc))
       |(check (= $$tails-closure (Union $$eps $$suffixes-abc)))
       |
       |; The binder is structural, not a menu of named templates.
       |(check (= $$iteration-reconstruct $$rows))
       |(check (= $$iteration-tails (TailsUnion $$rows)))
       |(check (= $$iteration-static $$sq))
       |(check (= $$iteration-static-union (Union $$sq $$rows)))
       |""".stripMargin

  val zipperProgram: String =
    s"""$corePrelude
       |
       |; zipper.egg: the same path-set language, extended with virtual derivatives.
       |
       |(datatype Zipper
       |  (TrieZ Space)
       |  (EmptyZ)
       |  (Descend String Zipper)
       |  (Child String Zipper)
       |  (UnionZ Zipper Zipper)
       |  (IntersectionZ Zipper Zipper)
       |  (SubtractionZ Zipper Zipper)
       |  (ProductZ Zipper Zipper)
       |  (WrapZ Path Zipper)
       |  (PrefixClosureZ Zipper)
       |  (PrefixClosureBelowZ Zipper)
       |  (TailsIntersectionZ Zipper)
       |  (PatchChildZ Zipper String Zipper))
       |
       |(datatype Context
       |  (RootCtx)
       |  (PatchCtx Context String Zipper))
       |
       |(relation terminal (Zipper))
       |(relation nonterminal (Zipper))
       |(relation empty-focus (Zipper))
       |(relation nonempty-focus (Zipper))
       |(relation has-key (Zipper String))
       |(relation cursor (Context Zipper))
       |(relation down-query (Context Zipper String))
       |(relation down (Context Zipper String Context Zipper))
       |(relation up (Context Zipper Context Zipper))
       |(relation plug-query (Context Zipper))
       |(relation plugged (Context Zipper Zipper))
       |
       |(rewrite (Descend item z) (Child item z))
       |(rewrite (TrieZ (Empty)) (EmptyZ))
       |(rewrite (UnionZ (EmptyZ) z) z)
       |(rewrite (UnionZ z (EmptyZ)) z)
       |(rewrite (UnionZ z z) z)
       |(rewrite (IntersectionZ (EmptyZ) z) (EmptyZ))
       |(rewrite (IntersectionZ z (EmptyZ)) (EmptyZ))
       |(rewrite (IntersectionZ z z) z)
       |(rewrite (SubtractionZ (EmptyZ) z) (EmptyZ))
       |(rewrite (SubtractionZ z (EmptyZ)) z)
       |(rewrite (SubtractionZ z z) (EmptyZ))
       |(rewrite (ProductZ (EmptyZ) z) (EmptyZ))
       |(rewrite (ProductZ z (EmptyZ)) (EmptyZ))
       |(rewrite (WrapZ p (EmptyZ)) (EmptyZ))
       |(rewrite (WrapZ (Eps) z) z)
       |
       |; Concrete movement delegates to the exact source-language quotient.
       |; Virtual movement pushes one requested child through the operator DAG.
       |(rewrite (Child item (EmptyZ)) (EmptyZ))
       |(rewrite (Child item (TrieZ source))
       |  (TrieZ (Unwrap source (Item item))))
       |(rewrite (Child item (UnionZ left right))
       |  (UnionZ (Child item left) (Child item right)))
       |(rewrite (Child item (IntersectionZ left right))
       |  (IntersectionZ (Child item left) (Child item right)))
       |(rewrite (Child item (SubtractionZ left right))
       |  (SubtractionZ (Child item left) (Child item right)))
       |(rewrite (Child item (WrapZ (Item item) z)) z)
       |(rewrite (Child item (WrapZ (Item other) z)) (EmptyZ)
       |  :when ((!= item other)))
       |(rewrite (Child item (WrapZ (Concat (Item item) rest) z))
       |  (WrapZ rest z))
       |(rewrite (Child item (WrapZ (Concat (Item other) rest) z)) (EmptyZ)
       |  :when ((!= item other)))
       |(rewrite (Child item (PrefixClosureZ z))
       |  (PrefixClosureBelowZ (Child item z)))
       |
       |; Product movement is driven by exact nullability of the left focus.
       |(rewrite (Child item (ProductZ left right))
       |  (UnionZ (ProductZ (Child item left) right) (Child item right))
       |  :when ((terminal left)))
       |(rewrite (Child item (ProductZ left right))
       |  (ProductZ (Child item left) right)
       |  :when ((nonterminal left)))
       |
       |; A closed two-head virtual frontier. Equal heads merge their tails before
       |; the meet; distinct heads meet the complete same-key derivatives.
       |(rewrite
       |  (TailsIntersectionZ
       |    (UnionZ (WrapZ (Item item) left) (WrapZ (Item item) right)))
       |  (UnionZ left right))
       |(rewrite
       |  (TailsIntersectionZ
       |    (UnionZ
       |      (WrapZ (Item left-head) left)
       |      (WrapZ (Item right-head) right)))
       |  (IntersectionZ left right)
       |  :when ((!= left-head right-head)))
       |
       |; Exact positive and negative observations. Negative information is a
       |; relation, never an equality between an approximation and an exact key set.
       |(rule ((= z (EmptyZ))) ((empty-focus z) (nonterminal z)))
       |(rule ((= z (TrieZ (Singleton (Eps))))) ((terminal z)))
       |(rule ((= z (TrieZ (Singleton (Item item)))))
       |      ((nonterminal z) (nonempty-focus z)))
       |(rule ((= z (TrieZ (Singleton (Concat (Item item) rest)))))
       |      ((nonterminal z) (nonempty-focus z)))
       |(rule ((terminal z)) ((nonempty-focus z)))
       |(rule ((= z (UnionZ left right)) (terminal left)) ((terminal z)))
       |(rule ((= z (UnionZ left right)) (terminal right)) ((terminal z)))
       |(rule ((= z (UnionZ left right)) (nonterminal left) (nonterminal right))
       |      ((nonterminal z)))
       |(rule ((= z (UnionZ left right)) (nonempty-focus left)) ((nonempty-focus z)))
       |(rule ((= z (UnionZ left right)) (nonempty-focus right)) ((nonempty-focus z)))
       |(rule ((= z (UnionZ left right)) (empty-focus left) (empty-focus right))
       |      ((empty-focus z)))
       |(rule ((= z (IntersectionZ left right)) (terminal left) (terminal right))
       |      ((terminal z)))
       |(rule ((= z (IntersectionZ left right)) (nonterminal left)) ((nonterminal z)))
       |(rule ((= z (IntersectionZ left right)) (nonterminal right)) ((nonterminal z)))
       |(rule ((= z (IntersectionZ left right)) (empty-focus left)) ((empty-focus z)))
       |(rule ((= z (IntersectionZ left right)) (empty-focus right)) ((empty-focus z)))
       |(rule ((= z (SubtractionZ left right)) (terminal left) (nonterminal right))
       |      ((terminal z)))
       |(rule ((= z (SubtractionZ left right)) (nonterminal left)) ((nonterminal z)))
       |(rule ((= z (SubtractionZ left right)) (terminal right)) ((nonterminal z)))
       |(rule ((= z (SubtractionZ left right)) (empty-focus left)) ((empty-focus z)))
       |(rule ((= z (ProductZ left right)) (terminal left) (terminal right))
       |      ((terminal z)))
       |(rule ((= z (ProductZ left right)) (nonterminal left)) ((nonterminal z)))
       |(rule ((= z (ProductZ left right)) (nonterminal right)) ((nonterminal z)))
       |(rule ((= z (ProductZ left right)) (empty-focus left)) ((empty-focus z)))
       |(rule ((= z (ProductZ left right)) (empty-focus right)) ((empty-focus z)))
       |(rule ((= z (WrapZ (Eps) src)) (terminal src)) ((terminal z)))
       |(rule ((= z (WrapZ (Item item) src))) ((nonterminal z)))
       |(rule ((= z (WrapZ (Concat (Item item) rest) src))) ((nonterminal z)))
       |(rule ((= z (WrapZ p src)) (empty-focus src)) ((empty-focus z)))
       |(rule ((= z (WrapZ p src)) (nonempty-focus src)) ((nonempty-focus z)))
       |(rule ((= z (PrefixClosureZ src))) ((nonterminal z)))
       |(rule ((= z (PrefixClosureZ src)) (empty-focus src)) ((empty-focus z)))
       |(rule ((= z (PrefixClosureBelowZ src)) (nonempty-focus src)) ((terminal z)))
       |(rule ((= z (PrefixClosureBelowZ src)) (empty-focus src))
       |      ((empty-focus z) (nonterminal z)))
       |(rule ((= child (Child item z)) (nonempty-focus child)) ((has-key z item)))
       |
       |; Focus/context movement records the original parent. Up and plug rebuild
       |; only the traversed spine through PatchChildZ.
       |(rewrite (PatchChildZ parent item (Child item parent)) parent)
       |(rewrite (Child item (PatchChildZ parent item replacement)) replacement)
       |(rewrite (Child other (PatchChildZ parent item replacement)) (Child other parent)
       |  :when ((!= item other)))
       |(rule ((down-query ctx focus item)
       |       (cursor ctx focus)
       |       (= child (Child item focus))
       |       (nonempty-focus child))
       |      ((down ctx focus item (PatchCtx ctx item focus) child)))
       |(rule ((down ctx focus item child-ctx child)) ((cursor child-ctx child)))
       |(rule ((= ctx (PatchCtx parent item original)) (cursor ctx focus))
       |      ((up ctx focus parent (PatchChildZ original item focus))))
       |(rule ((cursor ctx focus)) ((plug-query ctx focus)))
       |(rule ((plug-query (RootCtx) focus)) ((plugged (RootCtx) focus focus)))
       |(rule ((= ctx (PatchCtx parent item original)) (plug-query ctx focus))
       |      ((plug-query parent (PatchChildZ original item focus))))
       |(rule ((= ctx (PatchCtx parent item original))
       |       (plug-query ctx focus)
       |       (plugged parent (PatchChildZ original item focus) whole))
       |      ((plugged ctx focus whole)))
       |
       |$fixtures
       |(let $$za (TrieZ $$sa))
       |(let $$zb (TrieZ $$sb))
       |(let $$zc (TrieZ $$sc))
       |(let $$z0 (TrieZ $$s0))
       |(let $$z1 (TrieZ $$s1))
       |(let $$z2 (TrieZ $$s2))
       |(let $$virtual-rows
       |  (UnionZ
       |    (WrapZ $$a (UnionZ $$z0 $$z1))
       |    (WrapZ $$b (UnionZ $$z0 $$z2))))
       |(let $$tails-meet (TailsIntersectionZ $$virtual-rows))
       |(let $$prefix-child (Child "a" (PrefixClosureZ (TrieZ $$sabc))))
       |(let $$closure-product
       |  (ProductZ (PrefixClosureZ (TrieZ $$sa)) $$zb))
       |(let $$closure-product-hit (Child "b" (Child "a" $$closure-product)))
       |(let $$ctx (PatchCtx (RootCtx) "a" $$virtual-rows))
       |(let $$child-a (Child "a" $$virtual-rows))
       |(let $$child-b (Child "b" $$virtual-rows))
       |(let $$child-c (Child "c" $$virtual-rows))
       |(let $$tails-meet-0 (Child "0" $$tails-meet))
       |(let $$tails-meet-1 (Child "1" $$tails-meet))
       |
       |(cursor (RootCtx) $$virtual-rows)
       |(down-query (RootCtx) $$virtual-rows "a")
       |(run 24)
       |
       |; Movement is checked directly, not through a materialization axiom.
       |(check (= $$child-a (UnionZ $$z0 $$z1)))
       |(check (= $$child-b (UnionZ $$z0 $$z2)))
       |(check (= $$child-c (EmptyZ)))
       |(check (= $$tails-meet-0 (TrieZ (Singleton (Eps)))))
       |(check (= $$tails-meet-1 (EmptyZ)))
       |
       |; Interior prefix-closure nullability drives product movement.
       |(check (terminal $$prefix-child))
       |(check (terminal $$closure-product-hit))
       |
       |; A down/up round trip plugs the unchanged child back into its parent.
       |(check (down (RootCtx) $$virtual-rows "a" $$ctx (UnionZ $$z0 $$z1)))
       |(check (up $$ctx (UnionZ $$z0 $$z1) (RootCtx) $$virtual-rows))
       |(check (plugged (RootCtx) $$virtual-rows $$virtual-rows))
       |(check (plugged $$ctx (UnionZ $$z0 $$z1) $$virtual-rows))
       |""".stripMargin

  def write(root: JPath = Paths.get(".").toAbsolutePath.normalize()): Vector[JPath] =
    val artifacts = Vector(
      root.resolve("formal.egg") -> formalProgram,
      root.resolve("zipper.egg") -> zipperProgram,
    )
    artifacts.map { (path, program) =>
      Files.writeString(path, program, StandardCharsets.UTF_8)
      path
    }

class IllustrativeEggArtifactsTest extends munit.FunSuite:
  private val root = Paths.get(".").toAbsolutePath.normalize()

  test("root illustrative egg artifacts are generated from one shared prelude") {
    val formal = Files.readString(root.resolve("formal.egg"), StandardCharsets.UTF_8)
    val zipper = Files.readString(root.resolve("zipper.egg"), StandardCharsets.UTF_8)
    assertEquals(formal, IllustrativeEggArtifacts.formalProgram)
    assertEquals(zipper, IllustrativeEggArtifacts.zipperProgram)
    assert(formal.startsWith(IllustrativeEggArtifacts.corePrelude))
    assert(zipper.startsWith(IllustrativeEggArtifacts.corePrelude))
    assertEquals(formal.linesIterator.count(_ == IllustrativeEggArtifacts.PreludeEnd), 1)
    assertEquals(zipper.linesIterator.count(_ == IllustrativeEggArtifacts.PreludeEnd), 1)
  }

@main def generateIllustrativeEggArtifacts(): Unit =
  IllustrativeEggArtifacts.write().foreach(path => println(path.toString))
